package application;

import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;

public class createAutoPlanTab extends GridPane {
	
	private ComboBox<String> team1PosCB;
	private ComboBox<String> team1TaxiCB;
	private ComboBox<String> team2PosCB;
	private ComboBox<String> team2TaxiCB;
	private ComboBox<String> team3PosCB;
	private ComboBox<String> team3TaxiCB;
	private TextField team1SpeTF;
	private TextField team1AmpTF;
	private TextField team11stPickTF;
	private TextField team12ndPickTF;
	private TextField team13rdPickTF;
	private TextField team14thPickTF;
	private TextField team15thPickTF;
	private TextField team16thPickTF;
	private TextField team17thPickTF;
	private TextField team18thPickTF;
	private TextField team2SpeTF;
	private TextField team2AmpTF;
	private TextField team21stPickTF;
	private TextField team22ndPickTF;
	private TextField team23rdPickTF;
	private TextField team24thPickTF;
	private TextField team25thPickTF;
	private TextField team26thPickTF;
	private TextField team27thPickTF;
	private TextField team28thPickTF;
	private TextField team3SpeTF;
	private TextField team3AmpTF;
	private TextField team31stPickTF;
	private TextField team32ndPickTF;
	private TextField team33rdPickTF;
	private TextField team34thPickTF;
	private TextField team35thPickTF;
	private TextField team36thPickTF;
	private TextField team37thPickTF;
	private TextField team38thPickTF;
	
	public createAutoPlanTab() {
		this.add(new Label("First Team's Auto Info"), 0, 0);
		this.add(new Label("Auto Start Postion"), 0, 1);
		this.add(new Label("Auto Taxi"), 1, 1);
		this.add(new Label("Specker Notes"), 2, 1);
		this.add(new Label("Auto Amp Notes"), 3, 1);
		this.add(new Label("1st Note Picked Up"), 4, 1);
		this.add(new Label("2nd Note Picked Up"), 5, 1);
		this.add(new Label("3rd Note Picked Up"), 6, 1);
		this.add(new Label("4th Note Picked Up"), 7, 1);
		this.add(new Label("5th Note Picked Up"), 8, 1);
		this.add(new Label("6th Note Picked Up"), 9, 1);
		this.add(new Label("7th Note Picked Up"), 10, 1);
		this.add(new Label("8th Note Picked Up"), 11, 1);
		team1PosCB = new ComboBox<String>();
		team1TaxiCB = new ComboBox<String>();
		this.add(team1PosCB, 0, 2);
		this.add(team1TaxiCB, 1, 2);
		team1SpeTF = new TextField();
		team1AmpTF = new TextField();
		team11stPickTF = new TextField();
		team12ndPickTF = new TextField();
		team13rdPickTF = new TextField();
		team14thPickTF = new TextField();
		team15thPickTF = new TextField();
		team16thPickTF = new TextField();
		team17thPickTF = new TextField();
		team18thPickTF = new TextField();
		this.add(team1SpeTF, 2, 2);
		this.add(team1AmpTF, 3, 2);
		this.add(team11stPickTF, 4, 2);
		this.add(team12ndPickTF, 5, 2);
		this.add(team13rdPickTF, 6, 2);
		this.add(team14thPickTF, 7, 2);
		this.add(team15thPickTF, 8, 2);
		this.add(team16thPickTF, 9, 2);
		this.add(team17thPickTF, 10, 2);
		this.add(team18thPickTF, 11, 2);
		this.add(new Label("Second Team's Auto Info"), 0, 3);
		this.add(new Label("Auto Start Postion"), 0, 4);
		this.add(new Label("Auto Taxi"), 1, 4);
		this.add(new Label("Specker Notes"), 2, 4);
		this.add(new Label("Auto Amp Notes"), 3, 4);
		this.add(new Label("1st Note Picked Up"), 4, 4);
		this.add(new Label("2nd Note Picked Up"), 5, 4);
		this.add(new Label("3rd Note Picked Up"), 6, 4);
		this.add(new Label("4th Note Picked Up"), 7, 4);
		this.add(new Label("5th Note Picked Up"), 8, 4);
		this.add(new Label("6th Note Picked Up"), 9, 4);
		this.add(new Label("7th Note Picked Up"), 10, 4);
		this.add(new Label("8th Note Picked Up"), 11, 4);
		team2PosCB = new ComboBox<String>();
		team2TaxiCB = new ComboBox<String>();
		this.add(team2PosCB, 0, 5);
		this.add(team2TaxiCB, 1, 5);
		team2SpeTF = new TextField();
		team2AmpTF = new TextField();
		team21stPickTF = new TextField();
		team22ndPickTF = new TextField();
		team23rdPickTF = new TextField();
		team24thPickTF = new TextField();
		team25thPickTF = new TextField();
		team26thPickTF = new TextField();
		team27thPickTF = new TextField();
		team28thPickTF = new TextField();
		this.add(team2SpeTF, 2, 5);
		this.add(team2AmpTF, 3, 5);
		this.add(team21stPickTF, 4, 5);
		this.add(team22ndPickTF, 5, 5);
		this.add(team23rdPickTF, 6, 5);
		this.add(team24thPickTF, 7, 5);
		this.add(team25thPickTF, 8, 5);
		this.add(team26thPickTF, 9, 5);
		this.add(team27thPickTF, 10, 5);
		this.add(team28thPickTF, 11, 5);
		this.add(new Label("Third Team's Auto Info"), 0, 6);
		this.add(new Label("Auto Start Postion"), 0, 7);
		this.add(new Label("Auto Taxi"), 1, 7);
		this.add(new Label("Specker Notes"), 2, 7);
		this.add(new Label("Auto Amp Notes"), 3, 7);
		this.add(new Label("1st Note Picked Up"), 4, 7);
		this.add(new Label("2nd Note Picked Up"), 5, 7);
		this.add(new Label("3rd Note Picked Up"), 6, 7);
		this.add(new Label("4th Note Picked Up"), 7, 7);
		this.add(new Label("5th Note Picked Up"), 8, 7);
		this.add(new Label("6th Note Picked Up"), 9, 7);
		this.add(new Label("7th Note Picked Up"), 10, 7);
		this.add(new Label("8th Note Picked Up"), 11, 7);
		team3PosCB = new ComboBox<String>();
		team3TaxiCB = new ComboBox<String>();
		this.add(team3PosCB, 0, 8);
		this.add(team3TaxiCB, 1, 8);
		team3SpeTF = new TextField();
		team3AmpTF = new TextField();
		team31stPickTF = new TextField();
		team32ndPickTF = new TextField();
		team33rdPickTF = new TextField();
		team34thPickTF = new TextField();
		team35thPickTF = new TextField();
		team36thPickTF = new TextField();
		team37thPickTF = new TextField();
		team38thPickTF = new TextField();
		this.add(team3SpeTF, 2, 8);
		this.add(team3AmpTF, 3, 8);
		this.add(team31stPickTF, 4, 8);
		this.add(team32ndPickTF, 5, 8);
		this.add(team33rdPickTF, 6, 8);
		this.add(team34thPickTF, 7, 8);
		this.add(team35thPickTF, 8, 8);
		this.add(team36thPickTF, 9, 8);
		this.add(team37thPickTF, 10, 8);
		this.add(team38thPickTF, 11, 8);
	}
}
