package application;

import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;

public class createMatchPlanTab extends GridPane{
	
	private TextField team1CyAmpTF;
	private TextField team1CySpeTF;
	private TextField team1CyTraTF;
	private TextField team1CyFeeTF;
	private ComboBox<String> team1NumCB;
	private ComboBox<String> team1ClimbCB;
	private ComboBox<String> team1ClimbWithCB;
	private ComboBox<String> team1DefenseCB;
	private ComboBox<String> team1PathCB;
	private TextField team2CyAmpTF;
	private TextField team2CySpeTF;
	private TextField team2CyTraTF;
	private TextField team2CyFeeTF;
	private ComboBox<String> team2NumCB;
	private ComboBox<String> team2ClimbCB;
	private ComboBox<String> team2ClimbWithCB;
	private ComboBox<String> team2DefenseCB;
	private ComboBox<String> team2PathCB;
	private TextField team3CyAmpTF;
	private TextField team3CySpeTF;
	private TextField team3CyTraTF;
	private TextField team3CyFeeTF;
	private ComboBox<String> team3NumCB;
	private ComboBox<String> team3ClimbCB;
	private ComboBox<String> team3ClimbWithCB;
	private ComboBox<String> team3DefenseCB;
	private ComboBox<String> team3PathCB;
	private Button submitOurTeamB;
	//other Teams Stuff
	private ComboBox<String> team4NumCB;
	private ComboBox<String> team5NumCB;
	private ComboBox<String> team6NumCB;
	private Button submitOtherTeamsB;
	
	public createMatchPlanTab() {
		this.add(new Label("Goals For Bot 1:"), 0, 0);
		this.add(new Label("Team Num:"), 0, 1);
		this.add(new Label("Cycles In Amp"), 1, 1);
		this.add(new Label("Cycles in Speaker"), 2, 1);
		this.add(new Label("Cycles In Trap"), 3, 1);
		this.add(new Label("Feed Cycles"), 4, 1);
		this.add(new Label("Climb"), 5, 1);
		this.add(new Label("Climb with Others"), 6, 1);
		this.add(new Label("Defense"), 7, 1);
		this.add(new Label("Driving Path"), 8, 1);
		team1CyAmpTF = new TextField();
		team1CySpeTF = new TextField();
		team1CyTraTF = new TextField();
		team1CyFeeTF = new TextField();
		team1NumCB = new ComboBox<String>();
		team1NumCB.getItems().addAll("1234", "5678");
		team1ClimbCB = new ComboBox<String>();
		team1ClimbCB.getItems().addAll("Climbed", "Parked", "None");
		team1ClimbWithCB = new ComboBox<String>();
		team1ClimbWithCB.getItems().addAll("2 Bots", "1 Bot", "No Bots");
		team1DefenseCB = new ComboBox<String>();
		team1DefenseCB.getItems().addAll("Full Defense", "Opertunic Defense", "Light Defense", "No Defense");
		team1PathCB = new ComboBox<String>();
		team1PathCB.getItems().addAll("Under Stage", "Amp Side", "Source Side");
		this.add(team1CyAmpTF, 1, 2);
		this.add(team1CySpeTF, 2, 2);
		this.add(team1CyTraTF, 3, 2);
		this.add(team1CyFeeTF, 4, 2);
		this.add(team1NumCB, 0, 2);
		this.add(team1ClimbCB, 5, 2);
		this.add(team1ClimbWithCB, 6, 2);
		this.add(team1DefenseCB, 7, 2);
		this.add(team1PathCB, 8, 2);
		this.add(new Label("Goals For Bot 2:"), 0, 3);
		this.add(new Label("Team Num:"), 0, 4);
		this.add(new Label("Cycles In Amp"), 1, 4);
		this.add(new Label("Cycles in Speaker"), 2, 4);
		this.add(new Label("Cycles In Trap"), 3, 4);
		this.add(new Label("Feed Cycles"), 4, 4);
		this.add(new Label("Climb"), 5, 4);
		this.add(new Label("Climb with Others"), 6, 4);
		this.add(new Label("Defense"), 7, 4);
		this.add(new Label("Driving Path"), 8, 4);
		team2CyAmpTF = new TextField();
		team2CySpeTF = new TextField();
		team2CyTraTF = new TextField();
		team2CyFeeTF = new TextField();
		team2NumCB = new ComboBox<String>();
		team2NumCB.getItems().addAll("1234", "5678");
		team2ClimbCB = new ComboBox<String>();
		team2ClimbCB.getItems().addAll("Climbed", "Parked", "None");
		team2ClimbWithCB = new ComboBox<String>();
		team2ClimbWithCB.getItems().addAll("2 Bots", "1 Bot", "No Bots");
		team2DefenseCB = new ComboBox<String>();
		team2DefenseCB.getItems().addAll("Full Defense", "Opertunic Defense", "Light Defense", "No Defense");
		team2PathCB = new ComboBox<String>();
		team2PathCB.getItems().addAll("Under Stage", "Amp Side", "Source Side");
		this.add(team2CyAmpTF, 1, 5);
		this.add(team2CySpeTF, 2, 5);
		this.add(team2CyTraTF, 3, 5);
		this.add(team2CyFeeTF, 4, 5);
		this.add(team2NumCB, 0, 5);
		this.add(team2ClimbCB, 5, 5);
		this.add(team2ClimbWithCB, 6, 5);
		this.add(team2DefenseCB, 7, 5);
		this.add(team2PathCB, 8, 5);
		this.add(new Label("Goals For Bot 3:"), 0, 6);
		this.add(new Label("Team Num:"), 0, 7);
		this.add(new Label("Cycles In Amp"), 1, 7);
		this.add(new Label("Cycles in Speaker"), 2, 7);
		this.add(new Label("Cycles In Trap"), 3, 7);
		this.add(new Label("Feed Cycles"), 4, 7);
		this.add(new Label("Climb"), 5, 7);
		this.add(new Label("Climb with Others"), 6, 7);
		this.add(new Label("Defense"), 7, 7);
		this.add(new Label("Driving Path"), 8, 7);
		team3CyAmpTF = new TextField();
		team3CySpeTF = new TextField();
		team3CyTraTF = new TextField();
		team3CyFeeTF = new TextField();
		team3NumCB = new ComboBox<String>();
		team3NumCB.getItems().addAll("1234", "5678");
		team3ClimbCB = new ComboBox<String>();
		team3ClimbCB.getItems().addAll("Climbed", "Parked", "None");
		team3ClimbWithCB = new ComboBox<String>();
		team3ClimbWithCB.getItems().addAll("2 Bots", "1 Bot", "No Bots");
		team3DefenseCB = new ComboBox<String>();
		team3DefenseCB.getItems().addAll("Full Defense", "Opertunic Defense", "Light Defense", "No Defense");
		team3PathCB = new ComboBox<String>();
		team3PathCB.getItems().addAll("Under Stage", "Amp Side", "Source Side");
		this.add(team3CyAmpTF, 1, 8);
		this.add(team3CySpeTF, 2, 8);
		this.add(team3CyTraTF, 3, 8);
		this.add(team3CyFeeTF, 4, 8);
		this.add(team3NumCB, 0, 8);
		this.add(team3ClimbCB, 5, 8);
		this.add(team3ClimbWithCB, 6, 8);
		this.add(team3DefenseCB, 7, 8);
		this.add(team3PathCB, 8, 8);
		submitOurTeamB = new Button("Submit");
		this.add(submitOurTeamB, 0, 9);
		// Add stuff for other team
		this.add(new Label("Oppoints:"), 0, 10);
		this.add(new Label("Team 1"), 0, 11);
		this.add(new Label("Team 2"), 1, 11);
		this.add(new Label("Team 3"), 2, 11);
		team4NumCB = new ComboBox<String>();
		team4NumCB.getItems().addAll("1234", "5678");
		team5NumCB = new ComboBox<String>();
		team5NumCB.getItems().addAll("1234", "5678");
		team6NumCB = new ComboBox<String>();
		team6NumCB.getItems().addAll("1234", "5678");
		this.add(team4NumCB, 0, 12);
		this.add(team5NumCB, 1, 12);
		this.add(team6NumCB, 2, 12);
		submitOtherTeamsB = new Button("Submit");
		this.add(submitOtherTeamsB, 0, 13);
	}
}
