package application;

import java.util.ArrayList;
import java.util.List;

import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;

public class searchMatchTab extends GridPane implements EventHandler<ActionEvent>{
	
	private Button submitNonB;
	private Button submitPlayB;
	private ComboBox<String> teamCB;
	private TextField matchNumTF;
	private ComboBox<String> isPracCB;
	private ComboBox<String> isReplayCB;
	private List<Integer> listOfTeamNums;
	private MatchList mainML;
	private TeamList theTL;
	
	public searchMatchTab(List<Integer> importedListOfTeamNums, boolean imIsPlayoff, MatchList imML, TeamList imTeamList) {
		listOfTeamNums = importedListOfTeamNums;
		mainML = imML;
		theTL = imTeamList;
		if(imIsPlayoff == false) {
			Label selTeamL = new Label("Select Team:");
			Label selMatchNumL = new Label("Select Match Number:");
			Label selPracMatchL = new Label("Is It a Practice Match?");
			Label selRePlayL = new Label("Is It a Match Replay");
			selTeamL.setId("smallTitle");
			selMatchNumL.setId("smallTitle");
			selPracMatchL.setId("smallTitle");
			selRePlayL.setId("smallTitle");
			submitNonB = new Button("Submit");
			submitNonB.setOnAction(this);
			BorderPane selTeamBP = new BorderPane();
			BorderPane selMatchNumBP = new BorderPane();
			BorderPane selPracBP = new BorderPane();
			BorderPane selRePlayBP = new BorderPane();
			teamCB = new ComboBox<String>();
			addComboBoxItems();
			matchNumTF = new TextField();
			isPracCB = new ComboBox<String>();
			isPracCB.getItems().addAll("Yes", "No");
			isReplayCB = new ComboBox<String>();
			isReplayCB.getItems().addAll("Yes", "No");
			selTeamBP.setTop(selTeamL);
			selMatchNumBP.setTop(selMatchNumL);
			selPracBP.setTop(selPracMatchL);
			selRePlayBP.setTop(selRePlayL);
			selTeamBP.setCenter(teamCB);
			selMatchNumBP.setCenter(matchNumTF);
			selPracBP.setCenter(isPracCB);
			selRePlayBP.setCenter(isReplayCB);
			selTeamBP.setId("seMSelBp1");
			selMatchNumBP.setId("seMSelBp2");
			selPracBP.setId("seMSelBp3");
			selRePlayBP.setId("seMSelBp4");
			HBox selHB = new HBox(5);
			selHB.getChildren().addAll(selTeamBP, selMatchNumBP, selPracBP, selRePlayBP);
			this.add(new Label("    "), 0, 0);
			this.add(new Label("    "), 2, 0);
			this.add(selHB, 1, 1);
			this.add(submitNonB, 1, 3);
		}else {
			Label selTeamL = new Label("Select Team:  ");
			Label selMatchNumL = new Label("Select Match Number:  ");
			Label selRePlayL = new Label("Is It a Match Replay");
			selTeamL.setId("smallTitle");
			selMatchNumL.setId("smallTitle");
			selRePlayL.setId("smallTitle");
			submitPlayB = new Button("Submit");
			submitPlayB.setOnAction(this);
			BorderPane selTeamBP = new BorderPane();
			BorderPane selMatchNumBP = new BorderPane();
			BorderPane selRePlayBP = new BorderPane();
			teamCB = new ComboBox<String>();
			addComboBoxItems();
			matchNumTF = new TextField();
			isReplayCB = new ComboBox<String>();
			isReplayCB.getItems().addAll("Yes", "No");
			selTeamBP.setTop(selTeamL);
			selMatchNumBP.setTop(selMatchNumL);
			selRePlayBP.setTop(selRePlayL);
			selTeamBP.setCenter(teamCB);
			selMatchNumBP.setCenter(matchNumTF);
			selRePlayBP.setCenter(isReplayCB);
			selTeamBP.setId("seMSelBp1");
			selMatchNumBP.setId("seMSelBp2");
			selRePlayBP.setId("seMSelBp3");
			HBox selHB = new HBox(5);
			selHB.getChildren().addAll(selTeamBP, selMatchNumBP, selRePlayBP);
			this.add(new Label("    "), 0, 0);
			this.add(new Label("    "), 2, 0);
			this.add(new Label("    "), 2, 1);
			this.add(new Label("    "), 2, 2);
			this.add(new Label("    "), 2, 3);
			this.add(new Label("    "), 2, 4);
			this.add(new Label("    "), 2, 5);
			this.add(new Label("    "), 2, 6);
			this.add(new Label("    "), 2, 7);
			this.add(new Label("    "), 2, 8);
			this.add(new Label("    "), 2, 9);
			this.add(selHB, 1, 1);
			this.add(submitPlayB, 1, 3);
		}
	}
	
	private void addComboBoxItems() {
		String teamNumS;
		for (int i = 0; i < listOfTeamNums.size(); i++) {
			if (listOfTeamNums.get(i) != null) {
				teamNumS = Integer.toString(listOfTeamNums.get(i));
				teamCB.getItems().add(teamNumS);
			}
		}
	}

	@Override
	public void handle(ActionEvent event) {
		try {
			//Blue = false, Red = true
			if(event.getSource() == submitNonB){
				this.getChildren().clear();
				this.add(new Label("    "), 0, 0);
				this.add(new Label("    "), 2, 0);
				this.add(new Label("    "), 2, 1);
				this.add(new Label("    "), 2, 2);
				this.add(new Label("    "), 2, 3);
				this.add(new Label("    "), 2, 4);
				this.add(new Label("    "), 2, 5);
				this.add(new Label("    "), 2, 6);
				this.add(new Label("    "), 2, 7);
				this.add(new Label("    "), 2, 8);
				this.add(new Label("    "), 2, 9);
				System.out.print("BoopseM0");
				String selTeamNumS = teamCB.getSelectionModel().getSelectedItem();
				String matchNumS = matchNumTF.getText();
				String isPracS = isPracCB.getSelectionModel().getSelectedItem();
				String isReplayS = isReplayCB.getSelectionModel().getSelectedItem();
				System.out.print("BoopseM1");
				int selTeamNum = Integer.parseInt(selTeamNumS);
				int matchNum = Integer.parseInt(matchNumS);
				boolean isPrac = Boolean.parseBoolean(isPracS);
				boolean isReplay = Boolean.parseBoolean(isReplayS);
				System.out.print("BoopseM2");
				List<Match> teamsMatch = mainML.getMatchFromFullList(matchNum);
				System.out.print("BoopseM3");
				List<Match> blueTeams =  new ArrayList<>();
				List<Match> redTeams =  new ArrayList<>();
				TeamList redTs = new TeamList();
				TeamList blueTs = new TeamList();
				Boolean mainColor = null;
				System.out.print("BoopseM4");
				for(int i = 0; i < teamsMatch.size(); i++) {
					System.out.print("BoopseM5");
					Match m = teamsMatch.get(i);
					boolean mColor = m.getAllianceColor();
					System.out.print("BoopseM6");
					if(mColor == false) {
						System.out.print("BoopseM7");
						blueTeams.add(m);
						blueTs.listOfTeams.add(theTL.getATeam(m.getMatchTeamNum()));
						if(m.getMatchTeamNum() == selTeamNum) {
							System.out.print("BoopseM8");
							mainColor = false;
						}
					}else {
						System.out.print("BoopseM9");
						redTeams.add(m);
						redTs.listOfTeams.add(theTL.getATeam(m.getMatchTeamNum()));
						if(m.getMatchTeamNum() == selTeamNum) {
							System.out.print("BoopseM10");
							mainColor = true;
						}
					}
				}
				System.out.print("BoopseM11");
				HBox blueHB = new HBox(5);
				HBox redHB = new HBox(5);
				System.out.print("BoopseM12Blue:" + blueTeams.size() + "Red:" + redTeams.size());
				
				if(blueTeams.size() == 3) {
					System.out.print("BoopseM13Blue3");
					int teamNum1 = blueTeams.get(0).getMatchTeamNum();
					int teamNum2 = blueTeams.get(1).getMatchTeamNum();
					int teamNum3 = blueTeams.get(2).getMatchTeamNum();
					Label blue1TeamNumL = new Label(Integer.toString(teamNum1) + "'s Stats");
					Label blue2TeamNumL = new Label(Integer.toString(teamNum2) + "'s Stats");
					Label blue3TeamNumL = new Label(Integer.toString(teamNum3) + "'s Stats");
					blue1TeamNumL.setId("smallTitle");
					blue2TeamNumL.setId("smallTitle");
					blue3TeamNumL.setId("smallTitle");
					BorderPane blue1TeamNumBP = new BorderPane();
					BorderPane blue2TeamNumBP = new BorderPane();
					BorderPane blue3TeamNumBP = new BorderPane();
					blue1TeamNumBP.setCenter(blue1TeamNumL);
					blue2TeamNumBP.setCenter(blue2TeamNumL);
					blue3TeamNumBP.setCenter(blue3TeamNumL);
					Label blue1Cy = new Label(Integer.toString(blueTeams.get(0).getMatchAmp() + blueTeams.get(0).getMatchSpe() + blueTeams.get(0).getMatchTrap()));
					Label blue2Cy = new Label(Integer.toString(blueTeams.get(1).getMatchAmp() + blueTeams.get(1).getMatchSpe() + blueTeams.get(1).getMatchTrap()));
					Label blue3Cy = new Label(Integer.toString(blueTeams.get(2).getMatchAmp() + blueTeams.get(2).getMatchSpe() + blueTeams.get(2).getMatchTrap()));
					blue1Cy.setId("avgStat");
					blue2Cy.setId("avgStat");
					blue3Cy.setId("avgStat");
					Label blue1Amp = new Label(Integer.toString(blueTeams.get(0).getMatchAmp()));
					Label blue2Amp = new Label(Integer.toString(blueTeams.get(1).getMatchAmp()));
					Label blue3Amp = new Label(Integer.toString(blueTeams.get(2).getMatchAmp()));
					Label blue1Spe = new Label(Integer.toString(blueTeams.get(0).getMatchSpe()));
					Label blue2Spe = new Label(Integer.toString(blueTeams.get(1).getMatchSpe()));
					Label blue3Spe = new Label(Integer.toString(blueTeams.get(2).getMatchSpe()));
					Label blue1Trap = new Label(Integer.toString(blueTeams.get(0).getMatchTrap()));
					Label blue2Trap = new Label(Integer.toString(blueTeams.get(1).getMatchTrap()));
					Label blue3Trap = new Label(Integer.toString(blueTeams.get(2).getMatchTrap()));
					blue1Amp.setId("avgStat");
					blue2Amp.setId("avgStat");
					blue3Amp.setId("avgStat");
					blue1Spe.setId("avgStat");
					blue2Spe.setId("avgStat");
					blue3Spe.setId("avgStat");
					blue1Trap.setId("avgStat");
					blue2Trap.setId("avgStat");
					blue3Trap.setId("avgStat");
					Label blue1AvgCy = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgCycles()));
					Label blue2AvgCy = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgCycles()));
					Label blue3AvgCy = new Label(Double.toString(theTL.getATeam(teamNum3).getAvgCycles()));
					Label blue1AvgSpe = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgSpe()));
					Label blue2AvgSpe = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgSpe()));
					Label blue3AvgSpe = new Label(Double.toString(theTL.getATeam(teamNum3).getAvgSpe()));
					Label blue1AvgAmp = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgAmp()));
					Label blue2AvgAmp = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgAmp()));
					Label blue3AvgAmp = new Label(Double.toString(theTL.getATeam(teamNum3).getAvgAmp()));
					Label blue1AvgTrap = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgTrap()));
					Label blue2AvgTrap = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgTrap()));
					Label blue3AvgTrap = new Label(Double.toString(theTL.getATeam(teamNum3).getAvgTrap()));
					blue1AvgCy.setId("avgStat");
					blue2AvgCy.setId("avgStat");
					blue3AvgCy.setId("avgStat");
					blue1AvgSpe.setId("avgStat");
					blue2AvgSpe.setId("avgStat");
					blue3AvgSpe.setId("avgStat");
					blue1AvgAmp.setId("avgStat");
					blue2AvgAmp.setId("avgStat");
					blue3AvgAmp.setId("avgStat");
					blue1AvgTrap.setId("avgStat");
					blue2AvgTrap.setId("avgStat");
					blue3AvgTrap.setId("avgStat");
					Label blue1Cli = new Label(Integer.toString(blueTeams.get(0).getMatchClimb()));
					Label blue2Cli = new Label(Integer.toString(blueTeams.get(1).getMatchClimb()));
					Label blue3Cli = new Label(Integer.toString(blueTeams.get(2).getMatchClimb()));
					Label blue1AvgCli = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgClimb()));
					Label blue2AvgCli = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgClimb()));
					Label blue3AvgCli = new Label(Double.toString(theTL.getATeam(teamNum3).getAvgClimb()));
					blue1Cli.setId("avgStat");
					blue2Cli.setId("avgStat");
					blue3Cli.setId("avgStat");
					blue1AvgCli.setId("avgStat");
					blue2AvgCli.setId("avgStat");
					blue3AvgCli.setId("avgStat");
					Label blue1CyQL = new Label("Match Cycles");
					Label blue1SpeQL = new Label("Match Speaker");
					Label blue1AmpQL = new Label("Match Amp");
					Label blue1TrapQL = new Label("Match Trap");
					Label blue1CliQL = new Label("Match Climb");
					Label blue2CyQL = new Label("Match Cycles");
					Label blue2SpeQL = new Label("Match Speaker");
					Label blue2AmpQL = new Label("Match Amp");
					Label blue2TrapQL = new Label("Match Trap");
					Label blue2CliQL = new Label("Match Climb");
					Label blue3CyQL = new Label("Match Cycles");
					Label blue3SpeQL = new Label("Match Speaker");
					Label blue3AmpQL = new Label("Match Amp");
					Label blue3TrapQL = new Label("Match Trap");
					Label blue3CliQL = new Label("Match Climb");
					Label blue1AvgCyQL = new Label("Avg Cycles");
					Label blue1AvgSpeQL = new Label("Avg Speaker");
					Label blue1AvgAmpQL = new Label("Avg Amp");
					Label blue1AvgTrapQL = new Label("Avg Trap");
					Label blue1AvgCliQL = new Label("Avg Climb");
					Label blue2AvgCyQL = new Label("Avg Cycles");
					Label blue2AvgSpeQL = new Label("Avg Speaker");
					Label blue2AvgAmpQL = new Label("Avg Amp");
					Label blue2AvgTrapQL = new Label("Avg Trap");
					Label blue2AvgCliQL = new Label("Avg Climb");
					Label blue3AvgCyQL = new Label("Avg Cycles");
					Label blue3AvgSpeQL = new Label("Avg Speaker");
					Label blue3AvgAmpQL = new Label("Avg Amp");
					Label blue3AvgTrapQL = new Label("Avg Trap");
					Label blue3AvgCliQL = new Label("Avg Climb");
					blue1CyQL.setId("smallTitle");
					blue1SpeQL.setId("smallTitle");
					blue1AmpQL.setId("smallTitle");
					blue1TrapQL.setId("smallTitle");
					blue1CliQL.setId("smallTitle");
					blue2CyQL.setId("smallTitle");
					blue2SpeQL.setId("smallTitle");
					blue2AmpQL.setId("smallTitle");
					blue2TrapQL.setId("smallTitle");
					blue2CliQL.setId("smallTitle");
					blue3CyQL.setId("smallTitle");
					blue3SpeQL.setId("smallTitle");
					blue3AmpQL.setId("smallTitle");
					blue3TrapQL.setId("smallTitle");
					blue3CliQL.setId("smallTitle");
					blue1AvgCyQL.setId("smallTitle");
					blue1AvgSpeQL.setId("smallTitle");
					blue1AvgAmpQL.setId("smallTitle");
					blue1AvgTrapQL.setId("smallTitle");
					blue1AvgCliQL.setId("smallTitle");
					blue2AvgCyQL.setId("smallTitle");
					blue2AvgSpeQL.setId("smallTitle");
					blue2AvgAmpQL.setId("smallTitle");
					blue2AvgTrapQL.setId("smallTitle");
					blue2AvgCliQL.setId("smallTitle");
					blue3AvgCyQL.setId("smallTitle");
					blue3AvgSpeQL.setId("smallTitle");
					blue3AvgAmpQL.setId("smallTitle");
					blue3AvgTrapQL.setId("smallTitle");
					blue3AvgCliQL.setId("smallTitle");
					BorderPane blue1CyBP = new BorderPane();
					BorderPane blue1SpeBP = new BorderPane();
					BorderPane blue1AmpBP = new BorderPane();
					BorderPane blue1TrapBP = new BorderPane();
					BorderPane blue1CliBP = new BorderPane();
					BorderPane blue1CyAvgBP = new BorderPane();
					BorderPane blue1SpeAvgBP = new BorderPane();
					BorderPane blue1AmpAvgBP = new BorderPane();
					BorderPane blue1TrapAvgBP = new BorderPane();
					BorderPane blue1CliAvgBP = new BorderPane();
					BorderPane blue2CyBP = new BorderPane();
					BorderPane blue2SpeBP = new BorderPane();
					BorderPane blue2AmpBP = new BorderPane();
					BorderPane blue2TrapBP = new BorderPane();
					BorderPane blue2CliBP = new BorderPane();
					BorderPane blue2CyAvgBP = new BorderPane();
					BorderPane blue2SpeAvgBP = new BorderPane();
					BorderPane blue2AmpAvgBP = new BorderPane();
					BorderPane blue2TrapAvgBP = new BorderPane();
					BorderPane blue2CliAvgBP = new BorderPane();
					BorderPane blue3CyBP = new BorderPane();
					BorderPane blue3SpeBP = new BorderPane();
					BorderPane blue3AmpBP = new BorderPane();
					BorderPane blue3TrapBP = new BorderPane();
					BorderPane blue3CliBP = new BorderPane();
					BorderPane blue3CyAvgBP = new BorderPane();
					BorderPane blue3SpeAvgBP = new BorderPane();
					BorderPane blue3AmpAvgBP = new BorderPane();
					BorderPane blue3TrapAvgBP = new BorderPane();
					BorderPane blue3CliAvgBP = new BorderPane();
					blue1CyBP.setTop(blue1CyQL);
					blue1SpeBP.setTop(blue1SpeQL);
					blue1AmpBP.setTop(blue1AmpQL);
					blue1TrapBP.setTop(blue1TrapQL);
					blue1CliBP.setTop(blue1CliQL);
					blue1CyAvgBP.setTop(blue1AvgCyQL);
					blue1SpeAvgBP.setTop(blue1AvgSpeQL);
					blue1AmpAvgBP.setTop(blue1AvgAmpQL);
					blue1TrapAvgBP.setTop(blue1AvgTrapQL);
					blue1CliAvgBP.setTop(blue1AvgCliQL);
					blue2CyBP.setTop(blue2CyQL);
					blue2SpeBP.setTop(blue2SpeQL);
					blue2AmpBP.setTop(blue2AmpQL);
					blue2TrapBP.setTop(blue2TrapQL);
					blue2CliBP.setTop(blue2CliQL);
					blue2CyAvgBP.setTop(blue2AvgCyQL);
					blue2SpeAvgBP.setTop(blue2AvgSpeQL);
					blue2AmpAvgBP.setTop(blue2AvgAmpQL);
					blue2TrapAvgBP.setTop(blue2AvgTrapQL);
					blue2CliAvgBP.setTop(blue2AvgCliQL);
					blue3CyBP.setTop(blue3CyQL);
					blue3SpeBP.setTop(blue3SpeQL);
					blue3AmpBP.setTop(blue3AmpQL);
					blue3TrapBP.setTop(blue3TrapQL);
					blue3CliBP.setTop(blue3CliQL);
					blue3CyAvgBP.setTop(blue3AvgCyQL);
					blue3SpeAvgBP.setTop(blue3AvgSpeQL);
					blue3AmpAvgBP.setTop(blue3AvgAmpQL);
					blue3TrapAvgBP.setTop(blue3AvgTrapQL);
					blue3CliAvgBP.setTop(blue3AvgCliQL);
					blue1CyBP.setCenter(blue1Cy);
					blue1SpeBP.setCenter(blue1Spe);
					blue1AmpBP.setCenter(blue1Amp);
					blue1TrapBP.setCenter(blue1Trap);
					blue1CliBP.setCenter(blue1Cli);
					blue1CyAvgBP.setCenter(blue1AvgCy);
					blue1SpeAvgBP.setCenter(blue1AvgSpe);
					blue1AmpAvgBP.setCenter(blue1AvgAmp);
					blue1TrapAvgBP.setCenter(blue1AvgTrap);
					blue1CliAvgBP.setCenter(blue1AvgCli);
					blue2CyBP.setCenter(blue2Cy);
					blue2SpeBP.setCenter(blue2Spe);
					blue2AmpBP.setCenter(blue2Amp);
					blue2TrapBP.setCenter(blue2Trap);
					blue2CliBP.setCenter(blue2Cli);
					blue2CyAvgBP.setCenter(blue2AvgCy);
					blue2SpeAvgBP.setCenter(blue2AvgSpe);
					blue2AmpAvgBP.setCenter(blue2AvgAmp);
					blue2TrapAvgBP.setCenter(blue2AvgTrap);
					blue2CliAvgBP.setCenter(blue2AvgCli);
					blue3CyBP.setCenter(blue3Cy);
					blue3SpeBP.setCenter(blue3Spe);
					blue3AmpBP.setCenter(blue3Amp);
					blue3TrapBP.setCenter(blue3Trap);
					blue3CliBP.setCenter(blue3Cli);
					blue3CyAvgBP.setCenter(blue3AvgCy);
					blue3SpeAvgBP.setCenter(blue3AvgSpe);
					blue3AmpAvgBP.setCenter(blue3AvgAmp);
					blue3TrapAvgBP.setCenter(blue3AvgTrap);
					blue3CliAvgBP.setCenter(blue3AvgCli);
					if(mainColor == false) {
						blue1CyBP.setId("seMStatBP1");
						blue1SpeBP.setId("seMStatBP3");
						blue1AmpBP.setId("seMStatBP5");
						blue1TrapBP.setId("seMStatBP7");
						blue1CliBP.setId("seMStatBP9");
						blue1CyAvgBP.setId("seMStatBP2");
						blue1SpeAvgBP.setId("seMStatBP4");
						blue1AmpAvgBP.setId("seMStatBP6");
						blue1TrapAvgBP.setId("seMStatBP8");
						blue1CliAvgBP.setId("seMStatBP8");
						blue2CyBP.setId("seMStatBP9");
						blue2SpeBP.setId("seMStatBP7");
						blue2AmpBP.setId("seMStatBP5");
						blue2TrapBP.setId("seMStatBP3");
						blue2CliBP.setId("seMStatBP1");
						blue2CyAvgBP.setId("seMStatBP8");
						blue2SpeAvgBP.setId("seMStatBP6");
						blue2AmpAvgBP.setId("seMStatBP4");
						blue2TrapAvgBP.setId("seMStatBP2");
						blue2CliAvgBP.setId("seMStatBP2");
						blue3CyBP.setId("seMStatBP1");
						blue3SpeBP.setId("seMStatBP3");
						blue3AmpBP.setId("seMStatBP5");
						blue3TrapBP.setId("seMStatBP7");
						blue3CliBP.setId("seMStatBP9");
						blue3CyAvgBP.setId("seMStatBP2");
						blue3SpeAvgBP.setId("seMStatBP4");
						blue3AmpAvgBP.setId("seMStatBP6");
						blue3TrapAvgBP.setId("seMStatBP8");
						blue3CliAvgBP.setId("seMStatBP8");
						VBox blue1VB = new VBox(5);
						VBox blue2VB = new VBox(5);
						VBox blue3VB = new VBox(5);
						blue1VB.getChildren().addAll(blue1TeamNumBP, blue1CyBP, blue1SpeBP, blue1AmpBP, blue1TrapBP, blue1CliBP);
						blue2VB.getChildren().addAll(blue2TeamNumBP, blue2CyBP, blue2SpeBP, blue2AmpBP, blue2TrapBP, blue2CliBP);
						blue3VB.getChildren().addAll(blue3TeamNumBP, blue3CyBP, blue3SpeBP, blue3AmpBP, blue3TrapBP, blue3CliBP);
						blueHB.getChildren().addAll(blue1VB, blue2VB, blue3VB);
					}else {
						System.out.print("BoopseM0");
						blue1CyBP.setId("seMStatBP9");
						blue1SpeBP.setId("seMStatBP7");
						blue1AmpBP.setId("seMStatBP5");
						blue1TrapBP.setId("seMStatBP3");
						blue1CliBP.setId("seMStatBP1");
						blue1CyAvgBP.setId("seMStatBP8");
						blue1SpeAvgBP.setId("seMStatBP6");
						blue1AmpAvgBP.setId("seMStatBP4");
						blue1TrapAvgBP.setId("seMStatBP2");
						blue1CliAvgBP.setId("seMStatBP2");
						blue2CyBP.setId("seMStatBP1");
						blue2SpeBP.setId("seMStatBP3");
						blue2AmpBP.setId("seMStatBP5");
						blue2TrapBP.setId("seMStatBP7");
						blue2CliBP.setId("seMStatBP9");
						blue2CyAvgBP.setId("seMStatBP2");
						blue2SpeAvgBP.setId("seMStatBP4");
						blue2AmpAvgBP.setId("seMStatBP6");
						blue2TrapAvgBP.setId("seMStatBP8");
						blue2CliAvgBP.setId("seMStatBP8");
						blue3CyBP.setId("seMStatBP9");
						blue3SpeBP.setId("seMStatBP7");
						blue3AmpBP.setId("seMStatBP5");
						blue3TrapBP.setId("seMStatBP3");
						blue3CliBP.setId("seMStatBP1");
						blue3CyAvgBP.setId("seMStatBP8");
						blue3SpeAvgBP.setId("seMStatBP6");
						blue3AmpAvgBP.setId("seMStatBP4");
						blue3TrapAvgBP.setId("seMStatBP2");
						blue3CliAvgBP.setId("seMStatBP2");
						VBox blue1VB = new VBox(5);
						VBox blue2VB = new VBox(5);
						VBox blue3VB = new VBox(5);
						blue1VB.getChildren().addAll(blue1TeamNumBP, blue1CyBP, blue1SpeBP, blue1AmpBP, blue1TrapBP, blue1CliBP);
						blue2VB.getChildren().addAll(blue2TeamNumBP, blue2CyBP, blue2SpeBP, blue2AmpBP, blue2TrapBP, blue2CliBP);
						blue3VB.getChildren().addAll(blue3TeamNumBP, blue3CyBP, blue3SpeBP, blue3AmpBP, blue3TrapBP, blue3CliBP);
						blueHB.getChildren().addAll(blue1VB, blue2VB, blue3VB);
					}
				}else if(blueTeams.size() == 2) {
					System.out.print("BoopseM13Blue2");
					int teamNum1 = blueTeams.get(0).getMatchTeamNum();
					int teamNum2 = blueTeams.get(1).getMatchTeamNum();
					Label blue1TeamNumL = new Label(Integer.toString(teamNum1));
					Label blue2TeamNumL = new Label(Integer.toString(teamNum2));
					Label noDataLabel1L = new Label("No Data");
					blue1TeamNumL.setId("smallTitle");
					blue2TeamNumL.setId("smallTitle");
					noDataLabel1L.setId("smallTitle");
					BorderPane blue1TeamNumBP = new BorderPane();
					BorderPane blue2TeamNumBP = new BorderPane();
					BorderPane noData1BP = new BorderPane();
					blue1TeamNumBP.setCenter(blue1TeamNumL);
					blue2TeamNumBP.setCenter(blue2TeamNumL);
					noData1BP.setCenter(noDataLabel1L);
					Label blue1Cy = new Label(Integer.toString(blueTeams.get(0).getMatchAmp() + blueTeams.get(0).getMatchSpe() + blueTeams.get(0).getMatchTrap()));
					Label blue2Cy = new Label(Integer.toString(blueTeams.get(1).getMatchAmp() + blueTeams.get(1).getMatchSpe() + blueTeams.get(1).getMatchTrap()));
					blue1Cy.setId("avgStat");
					blue2Cy.setId("avgStat");
					Label blue1Amp = new Label(Integer.toString(blueTeams.get(0).getMatchAmp()));
					Label blue2Amp = new Label(Integer.toString(blueTeams.get(1).getMatchAmp()));
					Label blue1Spe = new Label(Integer.toString(blueTeams.get(0).getMatchSpe()));
					Label blue2Spe = new Label(Integer.toString(blueTeams.get(1).getMatchSpe()));
					Label blue1Trap = new Label(Integer.toString(blueTeams.get(0).getMatchTrap()));
					Label blue2Trap = new Label(Integer.toString(blueTeams.get(1).getMatchTrap()));
					blue1Amp.setId("avgStat");
					blue2Amp.setId("avgStat");
					blue1Spe.setId("avgStat");
					blue2Spe.setId("avgStat");
					blue1Trap.setId("avgStat");
					blue2Trap.setId("avgStat");
					Label blue1AvgCy = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgCycles()));
					Label blue2AvgCy = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgCycles()));
					Label blue1AvgSpe = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgSpe()));
					Label blue2AvgSpe = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgSpe()));
					Label blue1AvgAmp = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgAmp()));
					Label blue2AvgAmp = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgAmp()));
					Label blue1AvgTrap = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgTrap()));
					Label blue2AvgTrap = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgTrap()));
					blue1AvgCy.setId("avgStat");
					blue2AvgCy.setId("avgStat");
					blue1AvgSpe.setId("avgStat");
					blue2AvgSpe.setId("avgStat");
					blue1AvgAmp.setId("avgStat");
					blue2AvgAmp.setId("avgStat");
					blue1AvgTrap.setId("avgStat");
					blue2AvgTrap.setId("avgStat");
					Label blue1Cli = new Label(Integer.toString(blueTeams.get(0).getMatchClimb()));
					Label blue2Cli = new Label(Integer.toString(blueTeams.get(1).getMatchClimb()));
					Label blue1AvgCli = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgClimb()));
					Label blue2AvgCli = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgClimb()));
					blue1Cli.setId("avgStat");
					blue2Cli.setId("avgStat");
					blue1AvgCli.setId("avgStat");
					blue2AvgCli.setId("avgStat");
					Label blue1CyQL = new Label("Match Cycles");
					Label blue1SpeQL = new Label("Match Speaker");
					Label blue1AmpQL = new Label("Match Amp");
					Label blue1TrapQL = new Label("Match Trap");
					Label blue1CliQL = new Label("Match Climb");
					Label blue2CyQL = new Label("Match Cycles");
					Label blue2SpeQL = new Label("Match Speaker");
					Label blue2AmpQL = new Label("Match Amp");
					Label blue2TrapQL = new Label("Match Trap");
					Label blue2CliQL = new Label("Match Climb");
					Label blue1AvgCyQL = new Label("Avg Cycles");
					Label blue1AvgSpeQL = new Label("Avg Speaker");
					Label blue1AvgAmpQL = new Label("Avg Amp");
					Label blue1AvgTrapQL = new Label("Avg Trap");
					Label blue1AvgCliQL = new Label("Avg Climb");
					Label blue2AvgCyQL = new Label("Avg Cycles");
					Label blue2AvgSpeQL = new Label("Avg Speaker");
					Label blue2AvgAmpQL = new Label("Avg Amp");
					Label blue2AvgTrapQL = new Label("Avg Trap");
					Label blue2AvgCliQL = new Label("Avg Climb");
					blue1CyQL.setId("smallTitle");
					blue1SpeQL.setId("smallTitle");
					blue1AmpQL.setId("smallTitle");
					blue1TrapQL.setId("smallTitle");
					blue1CliQL.setId("smallTitle");
					blue2CyQL.setId("smallTitle");
					blue2SpeQL.setId("smallTitle");
					blue2AmpQL.setId("smallTitle");
					blue2TrapQL.setId("smallTitle");
					blue2CliQL.setId("smallTitle");
					blue1AvgCyQL.setId("smallTitle");
					blue1AvgSpeQL.setId("smallTitle");
					blue1AvgAmpQL.setId("smallTitle");
					blue1AvgTrapQL.setId("smallTitle");
					blue1AvgCliQL.setId("smallTitle");
					blue2AvgCyQL.setId("smallTitle");
					blue2AvgSpeQL.setId("smallTitle");
					blue2AvgAmpQL.setId("smallTitle");
					blue2AvgTrapQL.setId("smallTitle");
					blue2AvgCliQL.setId("smallTitle");
					BorderPane blue1CyBP = new BorderPane();
					BorderPane blue1SpeBP = new BorderPane();
					BorderPane blue1AmpBP = new BorderPane();
					BorderPane blue1TrapBP = new BorderPane();
					BorderPane blue1CliBP = new BorderPane();
					BorderPane blue1CyAvgBP = new BorderPane();
					BorderPane blue1SpeAvgBP = new BorderPane();
					BorderPane blue1AmpAvgBP = new BorderPane();
					BorderPane blue1TrapAvgBP = new BorderPane();
					BorderPane blue1CliAvgBP = new BorderPane();
					BorderPane blue2CyBP = new BorderPane();
					BorderPane blue2SpeBP = new BorderPane();
					BorderPane blue2AmpBP = new BorderPane();
					BorderPane blue2TrapBP = new BorderPane();
					BorderPane blue2CliBP = new BorderPane();
					BorderPane blue2CyAvgBP = new BorderPane();
					BorderPane blue2SpeAvgBP = new BorderPane();
					BorderPane blue2AmpAvgBP = new BorderPane();
					BorderPane blue2TrapAvgBP = new BorderPane();
					BorderPane blue2CliAvgBP = new BorderPane();
					blue1CyBP.setTop(blue1CyQL);
					blue1SpeBP.setTop(blue1SpeQL);
					blue1AmpBP.setTop(blue1AmpQL);
					blue1TrapBP.setTop(blue1TrapQL);
					blue1CliBP.setTop(blue1CliQL);
					blue1CyAvgBP.setTop(blue1AvgCyQL);
					blue1SpeAvgBP.setTop(blue1AvgSpeQL);
					blue1AmpAvgBP.setTop(blue1AvgAmpQL);
					blue1TrapAvgBP.setTop(blue1AvgTrapQL);
					blue1CliAvgBP.setTop(blue1AvgCliQL);
					blue2CyBP.setTop(blue1CyQL);
					blue2SpeBP.setTop(blue2SpeQL);
					blue2AmpBP.setTop(blue2AmpQL);
					blue2TrapBP.setTop(blue2TrapQL);
					blue2CliBP.setTop(blue2CliQL);
					blue2CyAvgBP.setTop(blue2AvgCyQL);
					blue2SpeAvgBP.setTop(blue2AvgSpeQL);
					blue2AmpAvgBP.setTop(blue2AvgAmpQL);
					blue2TrapAvgBP.setTop(blue2AvgTrapQL);
					blue2CliAvgBP.setTop(blue2AvgCliQL);
					blue1CyBP.setCenter(blue1Cy);
					blue1SpeBP.setCenter(blue1Spe);
					blue1AmpBP.setCenter(blue1Amp);
					blue1TrapBP.setCenter(blue1Trap);
					blue1CliBP.setCenter(blue1Cli);
					blue1CyAvgBP.setCenter(blue1AvgCy);
					blue1SpeAvgBP.setCenter(blue1AvgSpe);
					blue1AmpAvgBP.setCenter(blue1AvgAmp);
					blue1TrapAvgBP.setCenter(blue1AvgTrap);
					blue1CliAvgBP.setCenter(blue1AvgCli);
					blue2CyBP.setCenter(blue1Cy);
					blue2SpeBP.setCenter(blue2Spe);
					blue2AmpBP.setCenter(blue2Amp);
					blue2TrapBP.setCenter(blue2Trap);
					blue2CliBP.setCenter(blue2Cli);
					blue2CyAvgBP.setCenter(blue2AvgCy);
					blue2SpeAvgBP.setCenter(blue2AvgSpe);
					blue2AmpAvgBP.setCenter(blue2AvgAmp);
					blue2TrapAvgBP.setCenter(blue2AvgTrap);
					blue2CliAvgBP.setCenter(blue2AvgCli);
					if(mainColor == false) {
						blue1CyBP.setId("seMStatBP1");
						blue1SpeBP.setId("seMStatBP3");
						blue1AmpBP.setId("seMStatBP5");
						blue1TrapBP.setId("seMStatBP7");
						blue1CliBP.setId("seMStatBP9");
						blue1CyAvgBP.setId("seMStatBP2");
						blue1SpeAvgBP.setId("seMStatBP4");
						blue1AmpAvgBP.setId("seMStatBP6");
						blue1TrapAvgBP.setId("seMStatBP8");
						blue1CliAvgBP.setId("seMStatBP8");
						blue2CyBP.setId("seMStatBP9");
						blue2SpeBP.setId("seMStatBP7");
						blue2AmpBP.setId("seMStatBP5");
						blue2TrapBP.setId("seMStatBP3");
						blue2CliBP.setId("seMStatBP1");
						blue2CyAvgBP.setId("seMStatBP8");
						blue2SpeAvgBP.setId("seMStatBP6");
						blue2AmpAvgBP.setId("seMStatBP4");
						blue2TrapAvgBP.setId("seMStatBP2");
						blue2CliAvgBP.setId("seMStatBP2");
						noData1BP.setId("seMStatBP1");
						VBox blue1VB = new VBox(5);
						VBox blue2VB = new VBox(5);
						VBox blue3VB = new VBox(5);
						blue1VB.getChildren().addAll(blue1TeamNumBP, blue1CyBP, blue1SpeBP, blue1AmpBP, blue1TrapBP, blue1CliBP);
						blue2VB.getChildren().addAll(blue2TeamNumBP, blue2CyBP, blue2SpeBP, blue2AmpBP, blue2TrapBP, blue2CliBP);
						blue3VB.getChildren().add(noData1BP);
						blueHB.getChildren().addAll(blue1VB, blue2VB, blue3VB);
					}else {
						blue1CyBP.setId("seMStatBP9");
						blue1SpeBP.setId("seMStatBP7");
						blue1AmpBP.setId("seMStatBP5");
						blue1TrapBP.setId("seMStatBP3");
						blue1CliBP.setId("seMStatBP1");
						blue1CyAvgBP.setId("seMStatBP8");
						blue1SpeAvgBP.setId("seMStatBP6");
						blue1AmpAvgBP.setId("seMStatBP4");
						blue1TrapAvgBP.setId("seMStatBP2");
						blue1CliAvgBP.setId("seMStatBP2");
						blue2CyBP.setId("seMStatBP1");
						blue2SpeBP.setId("seMStatBP3");
						blue2AmpBP.setId("seMStatBP5");
						blue2TrapBP.setId("seMStatBP7");
						blue2CliBP.setId("seMStatBP9");
						blue2CyAvgBP.setId("seMStatBP2");
						blue2SpeAvgBP.setId("seMStatBP4");
						blue2AmpAvgBP.setId("seMStatBP6");
						blue2TrapAvgBP.setId("seMStatBP8");
						blue2CliAvgBP.setId("seMStatBP8");
						noData1BP.setId("seMStatBP9");
						VBox blue1VB = new VBox(5);
						VBox blue2VB = new VBox(5);
						VBox blue3VB = new VBox(5);
						blue1VB.getChildren().addAll(blue1TeamNumBP, blue1CyBP, blue1SpeBP, blue1AmpBP, blue1TrapBP, blue1CliBP);
						blue2VB.getChildren().addAll(blue2TeamNumBP, blue2CyBP, blue2SpeBP, blue2AmpBP, blue2TrapBP, blue2CliBP);
						blue3VB.getChildren().add(noData1BP);
						blueHB.getChildren().addAll(blue1VB, blue2VB, blue3VB);
					}
				}else if(blueTeams.size() == 1) {
					System.out.print("BoopseM13Blue1");
					int teamNum1 = blueTeams.get(0).getMatchTeamNum();
					Label blue1TeamNumL = new Label(Integer.toString(teamNum1));
					Label noDataLabel1L = new Label("No Data");
					Label noDataLabel2L = new Label("No Data");
					blue1TeamNumL.setId("smallTitle");
					noDataLabel1L.setId("smallTitle");
					noDataLabel2L.setId("smallTitle");
					BorderPane blue1TeamNumBP = new BorderPane();
					BorderPane noData1BP = new BorderPane();
					BorderPane noData2BP = new BorderPane();
					blue1TeamNumBP.setCenter(blue1TeamNumL);
					noData1BP.setCenter(noDataLabel1L);
					noData2BP.setCenter(noDataLabel2L);
					Label blue1Cy = new Label(Integer.toString(blueTeams.get(0).getMatchAmp() + blueTeams.get(0).getMatchSpe() + blueTeams.get(0).getMatchTrap()));
					blue1Cy.setId("avgStat");
					Label blue1Amp = new Label(Integer.toString(blueTeams.get(0).getMatchAmp()));
					Label blue1Spe = new Label(Integer.toString(blueTeams.get(0).getMatchSpe()));
					Label blue1Trap = new Label(Integer.toString(blueTeams.get(0).getMatchTrap()));
					blue1Amp.setId("avgStat");
					blue1Spe.setId("avgStat");
					blue1Trap.setId("avgStat");
					Label blue1AvgCy = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgCycles()));
					Label blue1AvgSpe = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgSpe()));
					Label blue1AvgAmp = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgAmp()));
					Label blue1AvgTrap = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgTrap()));
					blue1AvgCy.setId("avgStat");
					blue1AvgSpe.setId("avgStat");
					blue1AvgAmp.setId("avgStat");
					blue1AvgTrap.setId("avgStat");
					Label blue1Cli = new Label(Integer.toString(blueTeams.get(0).getMatchClimb()));
					Label blue1AvgCli = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgClimb()));
					blue1Cli.setId("avgStat");
					blue1AvgCli.setId("avgStat");
					Label blue1CyQL = new Label("Match Cycles");
					Label blue1SpeQL = new Label("Match Speaker");
					Label blue1AmpQL = new Label("Match Amp");
					Label blue1TrapQL = new Label("Match Trap");
					Label blue1CliQL = new Label("Match Climb");
					Label blue1AvgCyQL = new Label("Avg Cycles");
					Label blue1AvgSpeQL = new Label("Avg Speaker");
					Label blue1AvgAmpQL = new Label("Avg Amp");
					Label blue1AvgTrapQL = new Label("Avg Trap");
					Label blue1AvgCliQL = new Label("Avg Climb");
					blue1CyQL.setId("smallTitle");
					blue1SpeQL.setId("smallTitle");
					blue1AmpQL.setId("smallTitle");
					blue1TrapQL.setId("smallTitle");
					blue1CliQL.setId("smallTitle");
					blue1AvgCyQL.setId("smallTitle");
					blue1AvgSpeQL.setId("smallTitle");
					blue1AvgAmpQL.setId("smallTitle");
					blue1AvgTrapQL.setId("smallTitle");
					blue1AvgCliQL.setId("smallTitle");
					BorderPane blue1CyBP = new BorderPane();
					BorderPane blue1SpeBP = new BorderPane();
					BorderPane blue1AmpBP = new BorderPane();
					BorderPane blue1TrapBP = new BorderPane();
					BorderPane blue1CliBP = new BorderPane();
					BorderPane blue1CyAvgBP = new BorderPane();
					BorderPane blue1SpeAvgBP = new BorderPane();
					BorderPane blue1AmpAvgBP = new BorderPane();
					BorderPane blue1TrapAvgBP = new BorderPane();
					BorderPane blue1CliAvgBP = new BorderPane();
					blue1CyBP.setTop(blue1CyQL);
					blue1SpeBP.setTop(blue1SpeQL);
					blue1AmpBP.setTop(blue1AmpQL);
					blue1TrapBP.setTop(blue1TrapQL);
					blue1CliBP.setTop(blue1CliQL);
					blue1CyAvgBP.setTop(blue1AvgCyQL);
					blue1SpeAvgBP.setTop(blue1AvgSpeQL);
					blue1AmpAvgBP.setTop(blue1AvgAmpQL);
					blue1TrapAvgBP.setTop(blue1AvgTrapQL);
					blue1CliAvgBP.setTop(blue1AvgCliQL);
					blue1CyBP.setCenter(blue1Cy);
					blue1SpeBP.setCenter(blue1Spe);
					blue1AmpBP.setCenter(blue1Amp);
					blue1TrapBP.setCenter(blue1Trap);
					blue1CliBP.setCenter(blue1Cli);
					blue1CyAvgBP.setCenter(blue1AvgCy);
					blue1SpeAvgBP.setCenter(blue1AvgSpe);
					blue1AmpAvgBP.setCenter(blue1AvgAmp);
					blue1TrapAvgBP.setCenter(blue1AvgTrap);
					blue1CliAvgBP.setCenter(blue1AvgCli);
					if(mainColor == false) {
						blue1CyBP.setId("seMStatBP1");
						blue1SpeBP.setId("seMStatBP3");
						blue1AmpBP.setId("seMStatBP5");
						blue1TrapBP.setId("seMStatBP7");
						blue1CliBP.setId("seMStatBP9");
						blue1CyAvgBP.setId("seMStatBP2");
						blue1SpeAvgBP.setId("seMStatBP4");
						blue1AmpAvgBP.setId("seMStatBP6");
						blue1TrapAvgBP.setId("seMStatBP8");
						blue1CliAvgBP.setId("seMStatBP8");
						noData1BP.setId("seMStatBP9");
						noData2BP.setId("seMStatBP1");
						VBox blue1VB = new VBox(5);
						VBox blue2VB = new VBox(5);
						VBox blue3VB = new VBox(5);
						blue1VB.getChildren().addAll(blue1TeamNumBP, blue1CyBP, blue1SpeBP, blue1AmpBP, blue1TrapBP, blue1CliBP);
						blue2VB.getChildren().add(noData1BP);
						blue3VB.getChildren().add(noData2BP);
						blueHB.getChildren().addAll(blue1VB, blue2VB, blue3VB);
					}else {
						blue1CyBP.setId("seMStatBP9");
						blue1SpeBP.setId("seMStatBP7");
						blue1AmpBP.setId("seMStatBP5");
						blue1TrapBP.setId("seMStatBP3");
						blue1CliBP.setId("seMStatBP1");
						blue1CyAvgBP.setId("seMStatBP8");
						blue1SpeAvgBP.setId("seMStatBP6");
						blue1AmpAvgBP.setId("seMStatBP4");
						blue1TrapAvgBP.setId("seMStatBP2");
						blue1CliAvgBP.setId("seMStatBP2");
						noData1BP.setId("seMStatBP1");
						noData2BP.setId("seMStatBP9");
						VBox blue1VB = new VBox(5);
						VBox blue2VB = new VBox(5);
						VBox blue3VB = new VBox(5);
						blue1VB.getChildren().addAll(blue1TeamNumBP, blue1CyBP, blue1SpeBP, blue1AmpBP, blue1TrapBP, blue1CliBP);
						blue2VB.getChildren().add(noData1BP);
						blue3VB.getChildren().add(noData1BP);
						blueHB.getChildren().addAll(blue1VB, blue2VB, blue3VB);
					}
				}else if(blueTeams.size() == 0) {
					System.out.print("BoopseM13Blue0");
					Label noDataLabel1L = new Label("No Data");
					Label noDataLabel2L = new Label("No Data");
					Label noDataLabel3L = new Label("No Data");
					noDataLabel1L.setId("smallTitle");
					noDataLabel2L.setId("smallTitle");
					noDataLabel3L.setId("smallTitle");
					BorderPane noData1BP = new BorderPane();
					BorderPane noData2BP = new BorderPane();
					BorderPane noData3BP = new BorderPane();
					noData1BP.setCenter(noDataLabel1L);
					noData2BP.setCenter(noDataLabel2L);
					noData3BP.setCenter(noDataLabel3L);
					if(mainColor == false) {
						noData1BP.setId("seMStatBP9");
						noData2BP.setId("seMStatBP1");
						noData2BP.setId("seMStatBP9");
						VBox blue1VB = new VBox(5);
						VBox blue2VB = new VBox(5);
						VBox blue3VB = new VBox(5);
						blue1VB.getChildren().addAll(noData1BP);
						blue2VB.getChildren().add(noData2BP);
						blue3VB.getChildren().add(noData3BP);
						blueHB.getChildren().addAll(blue1VB, blue2VB, blue3VB);
					}else {
						noData1BP.setId("seMStatBP1");
						noData2BP.setId("seMStatBP9");
						noData2BP.setId("seMStatBP1");
						VBox blue1VB = new VBox(5);
						VBox blue2VB = new VBox(5);
						VBox blue3VB = new VBox(5);
						blue1VB.getChildren().addAll(noData1BP);
						blue2VB.getChildren().add(noData2BP);
						blue3VB.getChildren().add(noData3BP);
						blueHB.getChildren().addAll(blue1VB, blue2VB, blue3VB);
					}
				}
				if(redTeams.size() == 3) {
					System.out.print("BoopseM13red3");
					int teamNum1 = redTeams.get(0).getMatchTeamNum();
					int teamNum2 = redTeams.get(1).getMatchTeamNum();
					int teamNum3 = redTeams.get(2).getMatchTeamNum();
					Label red1TeamNumL = new Label(Integer.toString(teamNum1) + "'s Stats");
					Label red2TeamNumL = new Label(Integer.toString(teamNum2) + "'s Stats");
					Label red3TeamNumL = new Label(Integer.toString(teamNum3) + "'s Stats");
					red1TeamNumL.setId("smallTitle");
					red2TeamNumL.setId("smallTitle");
					red3TeamNumL.setId("smallTitle");
					BorderPane red1TeamNumBP = new BorderPane();
					BorderPane red2TeamNumBP = new BorderPane();
					BorderPane red3TeamNumBP = new BorderPane();
					red1TeamNumBP.setCenter(red1TeamNumL);
					red2TeamNumBP.setCenter(red2TeamNumL);
					red3TeamNumBP.setCenter(red3TeamNumL);
					Label red1Cy = new Label(Integer.toString(redTeams.get(0).getMatchAmp() + redTeams.get(0).getMatchSpe() + redTeams.get(0).getMatchTrap()));
					Label red2Cy = new Label(Integer.toString(redTeams.get(1).getMatchAmp() + redTeams.get(1).getMatchSpe() + redTeams.get(1).getMatchTrap()));
					Label red3Cy = new Label(Integer.toString(redTeams.get(2).getMatchAmp() + redTeams.get(2).getMatchSpe() + redTeams.get(2).getMatchTrap()));
					red1Cy.setId("avgStat");
					red2Cy.setId("avgStat");
					red3Cy.setId("avgStat");
					Label red1Amp = new Label(Integer.toString(redTeams.get(0).getMatchAmp()));
					Label red2Amp = new Label(Integer.toString(redTeams.get(1).getMatchAmp()));
					Label red3Amp = new Label(Integer.toString(redTeams.get(2).getMatchAmp()));
					Label red1Spe = new Label(Integer.toString(redTeams.get(0).getMatchSpe()));
					Label red2Spe = new Label(Integer.toString(redTeams.get(1).getMatchSpe()));
					Label red3Spe = new Label(Integer.toString(redTeams.get(2).getMatchSpe()));
					Label red1Trap = new Label(Integer.toString(redTeams.get(0).getMatchTrap()));
					Label red2Trap = new Label(Integer.toString(redTeams.get(1).getMatchTrap()));
					Label red3Trap = new Label(Integer.toString(redTeams.get(2).getMatchTrap()));
					red1Amp.setId("avgStat");
					red2Amp.setId("avgStat");
					red3Amp.setId("avgStat");
					red1Spe.setId("avgStat");
					red2Spe.setId("avgStat");
					red3Spe.setId("avgStat");
					red1Trap.setId("avgStat");
					red2Trap.setId("avgStat");
					red3Trap.setId("avgStat");
					Label red1AvgCy = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgCycles()));
					Label red2AvgCy = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgCycles()));
					Label red3AvgCy = new Label(Double.toString(theTL.getATeam(teamNum3).getAvgCycles()));
					Label red1AvgSpe = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgSpe()));
					Label red2AvgSpe = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgSpe()));
					Label red3AvgSpe = new Label(Double.toString(theTL.getATeam(teamNum3).getAvgSpe()));
					Label red1AvgAmp = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgAmp()));
					Label red2AvgAmp = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgAmp()));
					Label red3AvgAmp = new Label(Double.toString(theTL.getATeam(teamNum3).getAvgAmp()));
					Label red1AvgTrap = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgTrap()));
					Label red2AvgTrap = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgTrap()));
					Label red3AvgTrap = new Label(Double.toString(theTL.getATeam(teamNum3).getAvgTrap()));
					red1AvgCy.setId("avgStat");
					red2AvgCy.setId("avgStat");
					red3AvgCy.setId("avgStat");
					red1AvgSpe.setId("avgStat");
					red2AvgSpe.setId("avgStat");
					red3AvgSpe.setId("avgStat");
					red1AvgAmp.setId("avgStat");
					red2AvgAmp.setId("avgStat");
					red3AvgAmp.setId("avgStat");
					red1AvgTrap.setId("avgStat");
					red2AvgTrap.setId("avgStat");
					red3AvgTrap.setId("avgStat");
					Label red1Cli = new Label(Integer.toString(redTeams.get(0).getMatchClimb()));
					Label red2Cli = new Label(Integer.toString(redTeams.get(1).getMatchClimb()));
					Label red3Cli = new Label(Integer.toString(redTeams.get(2).getMatchClimb()));
					Label red1AvgCli = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgClimb()));
					Label red2AvgCli = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgClimb()));
					Label red3AvgCli = new Label(Double.toString(theTL.getATeam(teamNum3).getAvgClimb()));
					red1Cli.setId("avgStat");
					red2Cli.setId("avgStat");
					red3Cli.setId("avgStat");
					red1AvgCli.setId("avgStat");
					red2AvgCli.setId("avgStat");
					red3AvgCli.setId("avgStat");
					Label red1CyQL = new Label("Match Cycles");
					Label red1SpeQL = new Label("Match Speaker");
					Label red1AmpQL = new Label("Match Amp");
					Label red1TrapQL = new Label("Match Trap");
					Label red1CliQL = new Label("Match Climb");
					Label red2CyQL = new Label("Match Cycles");
					Label red2SpeQL = new Label("Match Speaker");
					Label red2AmpQL = new Label("Match Amp");
					Label red2TrapQL = new Label("Match Trap");
					Label red2CliQL = new Label("Match Climb");
					Label red3CyQL = new Label("Match Cycles");
					Label red3SpeQL = new Label("Match Speaker");
					Label red3AmpQL = new Label("Match Amp");
					Label red3TrapQL = new Label("Match Trap");
					Label red3CliQL = new Label("Match Climb");
					Label red1AvgCyQL = new Label("Avg Cycles");
					Label red1AvgSpeQL = new Label("Avg Speaker");
					Label red1AvgAmpQL = new Label("Avg Amp");
					Label red1AvgTrapQL = new Label("Avg Trap");
					Label red1AvgCliQL = new Label("Avg Climb");
					Label red2AvgCyQL = new Label("Avg Cycles");
					Label red2AvgSpeQL = new Label("Avg Speaker");
					Label red2AvgAmpQL = new Label("Avg Amp");
					Label red2AvgTrapQL = new Label("Avg Trap");
					Label red2AvgCliQL = new Label("Avg Climb");
					Label red3AvgCyQL = new Label("Avg Cycles");
					Label red3AvgSpeQL = new Label("Avg Speaker");
					Label red3AvgAmpQL = new Label("Avg Amp");
					Label red3AvgTrapQL = new Label("Avg Trap");
					Label red3AvgCliQL = new Label("Avg Climb");
					red1CyQL.setId("smallTitle");
					red1SpeQL.setId("smallTitle");
					red1AmpQL.setId("smallTitle");
					red1TrapQL.setId("smallTitle");
					red1CliQL.setId("smallTitle");
					red2CyQL.setId("smallTitle");
					red2SpeQL.setId("smallTitle");
					red2AmpQL.setId("smallTitle");
					red2TrapQL.setId("smallTitle");
					red2CliQL.setId("smallTitle");
					red3CyQL.setId("smallTitle");
					red3SpeQL.setId("smallTitle");
					red3AmpQL.setId("smallTitle");
					red3TrapQL.setId("smallTitle");
					red3CliQL.setId("smallTitle");
					red1AvgCyQL.setId("smallTitle");
					red1AvgSpeQL.setId("smallTitle");
					red1AvgAmpQL.setId("smallTitle");
					red1AvgTrapQL.setId("smallTitle");
					red1AvgCliQL.setId("smallTitle");
					red2AvgCyQL.setId("smallTitle");
					red2AvgSpeQL.setId("smallTitle");
					red2AvgAmpQL.setId("smallTitle");
					red2AvgTrapQL.setId("smallTitle");
					red2AvgCliQL.setId("smallTitle");
					red3AvgCyQL.setId("smallTitle");
					red3AvgSpeQL.setId("smallTitle");
					red3AvgAmpQL.setId("smallTitle");
					red3AvgTrapQL.setId("smallTitle");
					red3AvgCliQL.setId("smallTitle");
					BorderPane red1CyBP = new BorderPane();
					BorderPane red1SpeBP = new BorderPane();
					BorderPane red1AmpBP = new BorderPane();
					BorderPane red1TrapBP = new BorderPane();
					BorderPane red1CliBP = new BorderPane();
					BorderPane red1CyAvgBP = new BorderPane();
					BorderPane red1SpeAvgBP = new BorderPane();
					BorderPane red1AmpAvgBP = new BorderPane();
					BorderPane red1TrapAvgBP = new BorderPane();
					BorderPane red1CliAvgBP = new BorderPane();
					BorderPane red2CyBP = new BorderPane();
					BorderPane red2SpeBP = new BorderPane();
					BorderPane red2AmpBP = new BorderPane();
					BorderPane red2TrapBP = new BorderPane();
					BorderPane red2CliBP = new BorderPane();
					BorderPane red2CyAvgBP = new BorderPane();
					BorderPane red2SpeAvgBP = new BorderPane();
					BorderPane red2AmpAvgBP = new BorderPane();
					BorderPane red2TrapAvgBP = new BorderPane();
					BorderPane red2CliAvgBP = new BorderPane();
					BorderPane red3CyBP = new BorderPane();
					BorderPane red3SpeBP = new BorderPane();
					BorderPane red3AmpBP = new BorderPane();
					BorderPane red3TrapBP = new BorderPane();
					BorderPane red3CliBP = new BorderPane();
					BorderPane red3CyAvgBP = new BorderPane();
					BorderPane red3SpeAvgBP = new BorderPane();
					BorderPane red3AmpAvgBP = new BorderPane();
					BorderPane red3TrapAvgBP = new BorderPane();
					BorderPane red3CliAvgBP = new BorderPane();
					red1CyBP.setTop(red1CyQL);
					red1SpeBP.setTop(red1SpeQL);
					red1AmpBP.setTop(red1AmpQL);
					red1TrapBP.setTop(red1TrapQL);
					red1CliBP.setTop(red1CliQL);
					red1CyAvgBP.setTop(red1AvgCyQL);
					red1SpeAvgBP.setTop(red1AvgSpeQL);
					red1AmpAvgBP.setTop(red1AvgAmpQL);
					red1TrapAvgBP.setTop(red1AvgTrapQL);
					red1CliAvgBP.setTop(red1AvgCliQL);
					red2CyBP.setTop(red2CyQL);
					red2SpeBP.setTop(red2SpeQL);
					red2AmpBP.setTop(red2AmpQL);
					red2TrapBP.setTop(red2TrapQL);
					red2CliBP.setTop(red2CliQL);
					red2CyAvgBP.setTop(red2AvgCyQL);
					red2SpeAvgBP.setTop(red2AvgSpeQL);
					red2AmpAvgBP.setTop(red2AvgAmpQL);
					red2TrapAvgBP.setTop(red2AvgTrapQL);
					red2CliAvgBP.setTop(red2AvgCliQL);
					red3CyBP.setTop(red3CyQL);
					red3SpeBP.setTop(red3SpeQL);
					red3AmpBP.setTop(red3AmpQL);
					red3TrapBP.setTop(red3TrapQL);
					red3CliBP.setTop(red3CliQL);
					red3CyAvgBP.setTop(red3AvgCyQL);
					red3SpeAvgBP.setTop(red3AvgSpeQL);
					red3AmpAvgBP.setTop(red3AvgAmpQL);
					red3TrapAvgBP.setTop(red3AvgTrapQL);
					red3CliAvgBP.setTop(red3AvgCliQL);
					red1CyBP.setCenter(red1Cy);
					red1SpeBP.setCenter(red1Spe);
					red1AmpBP.setCenter(red1Amp);
					red1TrapBP.setCenter(red1Trap);
					red1CliBP.setCenter(red1Cli);
					red1CyAvgBP.setCenter(red1AvgCy);
					red1SpeAvgBP.setCenter(red1AvgSpe);
					red1AmpAvgBP.setCenter(red1AvgAmp);
					red1TrapAvgBP.setCenter(red1AvgTrap);
					red1CliAvgBP.setCenter(red1AvgCli);
					red2CyBP.setCenter(red2Cy);
					red2SpeBP.setCenter(red2Spe);
					red2AmpBP.setCenter(red2Amp);
					red2TrapBP.setCenter(red2Trap);
					red2CliBP.setCenter(red2Cli);
					red2CyAvgBP.setCenter(red2AvgCy);
					red2SpeAvgBP.setCenter(red2AvgSpe);
					red2AmpAvgBP.setCenter(red2AvgAmp);
					red2TrapAvgBP.setCenter(red2AvgTrap);
					red2CliAvgBP.setCenter(red2AvgCli);
					red3CyBP.setCenter(red3Cy);
					red3SpeBP.setCenter(red3Spe);
					red3AmpBP.setCenter(red3Amp);
					red3TrapBP.setCenter(red3Trap);
					red3CliBP.setCenter(red3Cli);
					red3CyAvgBP.setCenter(red3AvgCy);
					red3SpeAvgBP.setCenter(red3AvgSpe);
					red3AmpAvgBP.setCenter(red3AvgAmp);
					red3TrapAvgBP.setCenter(red3AvgTrap);
					red3CliAvgBP.setCenter(red3AvgCli);
					if(mainColor == false) {
						red1CyBP.setId("seMStatBP1");
						red1SpeBP.setId("seMStatBP3");
						red1AmpBP.setId("seMStatBP5");
						red1TrapBP.setId("seMStatBP7");
						red1CliBP.setId("seMStatBP9");
						red1CyAvgBP.setId("seMStatBP2");
						red1SpeAvgBP.setId("seMStatBP4");
						red1AmpAvgBP.setId("seMStatBP6");
						red1TrapAvgBP.setId("seMStatBP8");
						red1CliAvgBP.setId("seMStatBP8");
						red2CyBP.setId("seMStatBP9");
						red2SpeBP.setId("seMStatBP7");
						red2AmpBP.setId("seMStatBP5");
						red2TrapBP.setId("seMStatBP3");
						red2CliBP.setId("seMStatBP1");
						red2CyAvgBP.setId("seMStatBP8");
						red2SpeAvgBP.setId("seMStatBP6");
						red2AmpAvgBP.setId("seMStatBP4");
						red2TrapAvgBP.setId("seMStatBP2");
						red2CliAvgBP.setId("seMStatBP2");
						red3CyBP.setId("seMStatBP1");
						red3SpeBP.setId("seMStatBP3");
						red3AmpBP.setId("seMStatBP5");
						red3TrapBP.setId("seMStatBP7");
						red3CliBP.setId("seMStatBP9");
						red3CyAvgBP.setId("seMStatBP2");
						red3SpeAvgBP.setId("seMStatBP4");
						red3AmpAvgBP.setId("seMStatBP6");
						red3TrapAvgBP.setId("seMStatBP8");
						red3CliAvgBP.setId("seMStatBP8");
						VBox red1VB = new VBox(5);
						VBox red2VB = new VBox(5);
						VBox red3VB = new VBox(5);
						red1VB.getChildren().addAll(red1TeamNumBP, red1CyBP, red1SpeBP, red1AmpBP, red1TrapBP, red1CliBP);
						red2VB.getChildren().addAll(red2TeamNumBP, red2CyBP, red2SpeBP, red2AmpBP, red2TrapBP, red2CliBP);
						red3VB.getChildren().addAll(red3TeamNumBP, red3CyBP, red3SpeBP, red3AmpBP, red3TrapBP, red3CliBP);
						redHB.getChildren().addAll(red1VB, red2VB, red3VB);
					}else {
						red1CyBP.setId("seMStatBP9");
						red1SpeBP.setId("seMStatBP7");
						red1AmpBP.setId("seMStatBP5");
						red1TrapBP.setId("seMStatBP3");
						red1CliBP.setId("seMStatBP1");
						red1CyAvgBP.setId("seMStatBP8");
						red1SpeAvgBP.setId("seMStatBP6");
						red1AmpAvgBP.setId("seMStatBP4");
						red1TrapAvgBP.setId("seMStatBP2");
						red1CliAvgBP.setId("seMStatBP2");
						red2CyBP.setId("seMStatBP1");
						red2SpeBP.setId("seMStatBP3");
						red2AmpBP.setId("seMStatBP5");
						red2TrapBP.setId("seMStatBP7");
						red2CliBP.setId("seMStatBP9");
						red2CyAvgBP.setId("seMStatBP2");
						red2SpeAvgBP.setId("seMStatBP4");
						red2AmpAvgBP.setId("seMStatBP6");
						red2TrapAvgBP.setId("seMStatBP8");
						red2CliAvgBP.setId("seMStatBP8");
						red3CyBP.setId("seMStatBP9");
						red3SpeBP.setId("seMStatBP7");
						red3AmpBP.setId("seMStatBP5");
						red3TrapBP.setId("seMStatBP3");
						red3CliBP.setId("seMStatBP1");
						red3CyAvgBP.setId("seMStatBP8");
						red3SpeAvgBP.setId("seMStatBP6");
						red3AmpAvgBP.setId("seMStatBP4");
						red3TrapAvgBP.setId("seMStatBP2");
						red3CliAvgBP.setId("seMStatBP2");
						VBox red1VB = new VBox(5);
						VBox red2VB = new VBox(5);
						VBox red3VB = new VBox(5);
						red1VB.getChildren().addAll(red1TeamNumBP, red1CyBP, red1SpeBP, red1AmpBP, red1TrapBP, red1CliBP);
						red2VB.getChildren().addAll(red2TeamNumBP, red2CyBP, red2SpeBP, red2AmpBP, red2TrapBP, red2CliBP);
						red3VB.getChildren().addAll(red3TeamNumBP, red3CyBP, red3SpeBP, red3AmpBP, red3TrapBP, red3CliBP);
						redHB.getChildren().addAll(red1VB, red2VB, red3VB);
					}
				}else if(redTeams.size() == 2) {
					System.out.print("BoopseM13red2");
					int teamNum1 = redTeams.get(0).getMatchTeamNum();
					int teamNum2 = redTeams.get(1).getMatchTeamNum();
					Label red1TeamNumL = new Label(Integer.toString(teamNum1));
					Label red2TeamNumL = new Label(Integer.toString(teamNum2));
					Label noDataLabel1L = new Label("No Data");
					red1TeamNumL.setId("smallTitle");
					red2TeamNumL.setId("smallTitle");
					noDataLabel1L.setId("smallTitle");
					BorderPane red1TeamNumBP = new BorderPane();
					BorderPane red2TeamNumBP = new BorderPane();
					BorderPane noData1BP = new BorderPane();
					red1TeamNumBP.setCenter(red1TeamNumL);
					red2TeamNumBP.setCenter(red2TeamNumL);
					noData1BP.setCenter(noDataLabel1L);
					Label red1Cy = new Label(Integer.toString(redTeams.get(0).getMatchAmp() + redTeams.get(0).getMatchSpe() + redTeams.get(0).getMatchTrap()));
					Label red2Cy = new Label(Integer.toString(redTeams.get(1).getMatchAmp() + redTeams.get(1).getMatchSpe() + redTeams.get(1).getMatchTrap()));
					red1Cy.setId("avgStat");
					red2Cy.setId("avgStat");
					Label red1Amp = new Label(Integer.toString(redTeams.get(0).getMatchAmp()));
					Label red2Amp = new Label(Integer.toString(redTeams.get(1).getMatchAmp()));
					Label red1Spe = new Label(Integer.toString(redTeams.get(0).getMatchSpe()));
					Label red2Spe = new Label(Integer.toString(redTeams.get(1).getMatchSpe()));
					Label red1Trap = new Label(Integer.toString(redTeams.get(0).getMatchTrap()));
					Label red2Trap = new Label(Integer.toString(redTeams.get(1).getMatchTrap()));
					red1Amp.setId("avgStat");
					red2Amp.setId("avgStat");
					red1Spe.setId("avgStat");
					red2Spe.setId("avgStat");
					red1Trap.setId("avgStat");
					red2Trap.setId("avgStat");
					Label red1AvgCy = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgCycles()));
					Label red2AvgCy = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgCycles()));
					Label red1AvgSpe = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgSpe()));
					Label red2AvgSpe = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgSpe()));
					Label red1AvgAmp = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgAmp()));
					Label red2AvgAmp = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgAmp()));
					Label red1AvgTrap = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgTrap()));
					Label red2AvgTrap = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgTrap()));
					red1AvgCy.setId("avgStat");
					red2AvgCy.setId("avgStat");
					red1AvgSpe.setId("avgStat");
					red2AvgSpe.setId("avgStat");
					red1AvgAmp.setId("avgStat");
					red2AvgAmp.setId("avgStat");
					red1AvgTrap.setId("avgStat");
					red2AvgTrap.setId("avgStat");
					Label red1Cli = new Label(Integer.toString(redTeams.get(0).getMatchClimb()));
					Label red2Cli = new Label(Integer.toString(redTeams.get(1).getMatchClimb()));
					Label red1AvgCli = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgClimb()));
					Label red2AvgCli = new Label(Double.toString(theTL.getATeam(teamNum2).getAvgClimb()));
					red1Cli.setId("avgStat");
					red2Cli.setId("avgStat");
					red1AvgCli.setId("avgStat");
					red2AvgCli.setId("avgStat");
					Label red1CyQL = new Label("Match Cycles");
					Label red1SpeQL = new Label("Match Speaker");
					Label red1AmpQL = new Label("Match Amp");
					Label red1TrapQL = new Label("Match Trap");
					Label red1CliQL = new Label("Match Climb");
					Label red2CyQL = new Label("Match Cycles");
					Label red2SpeQL = new Label("Match Speaker");
					Label red2AmpQL = new Label("Match Amp");
					Label red2TrapQL = new Label("Match Trap");
					Label red2CliQL = new Label("Match Climb");
					Label red1AvgCyQL = new Label("Avg Cycles");
					Label red1AvgSpeQL = new Label("Avg Speaker");
					Label red1AvgAmpQL = new Label("Avg Amp");
					Label red1AvgTrapQL = new Label("Avg Trap");
					Label red1AvgCliQL = new Label("Avg Climb");
					Label red2AvgCyQL = new Label("Avg Cycles");
					Label red2AvgSpeQL = new Label("Avg Speaker");
					Label red2AvgAmpQL = new Label("Avg Amp");
					Label red2AvgTrapQL = new Label("Avg Trap");
					Label red2AvgCliQL = new Label("Avg Climb");
					red1CyQL.setId("smallTitle");
					red1SpeQL.setId("smallTitle");
					red1AmpQL.setId("smallTitle");
					red1TrapQL.setId("smallTitle");
					red1CliQL.setId("smallTitle");
					red2CyQL.setId("smallTitle");
					red2SpeQL.setId("smallTitle");
					red2AmpQL.setId("smallTitle");
					red2TrapQL.setId("smallTitle");
					red2CliQL.setId("smallTitle");
					red1AvgCyQL.setId("smallTitle");
					red1AvgSpeQL.setId("smallTitle");
					red1AvgAmpQL.setId("smallTitle");
					red1AvgTrapQL.setId("smallTitle");
					red1AvgCliQL.setId("smallTitle");
					red2AvgCyQL.setId("smallTitle");
					red2AvgSpeQL.setId("smallTitle");
					red2AvgAmpQL.setId("smallTitle");
					red2AvgTrapQL.setId("smallTitle");
					red2AvgCliQL.setId("smallTitle");
					BorderPane red1CyBP = new BorderPane();
					BorderPane red1SpeBP = new BorderPane();
					BorderPane red1AmpBP = new BorderPane();
					BorderPane red1TrapBP = new BorderPane();
					BorderPane red1CliBP = new BorderPane();
					BorderPane red1CyAvgBP = new BorderPane();
					BorderPane red1SpeAvgBP = new BorderPane();
					BorderPane red1AmpAvgBP = new BorderPane();
					BorderPane red1TrapAvgBP = new BorderPane();
					BorderPane red1CliAvgBP = new BorderPane();
					BorderPane red2CyBP = new BorderPane();
					BorderPane red2SpeBP = new BorderPane();
					BorderPane red2AmpBP = new BorderPane();
					BorderPane red2TrapBP = new BorderPane();
					BorderPane red2CliBP = new BorderPane();
					BorderPane red2CyAvgBP = new BorderPane();
					BorderPane red2SpeAvgBP = new BorderPane();
					BorderPane red2AmpAvgBP = new BorderPane();
					BorderPane red2TrapAvgBP = new BorderPane();
					BorderPane red2CliAvgBP = new BorderPane();
					red1CyBP.setTop(red1CyQL);
					red1SpeBP.setTop(red1SpeQL);
					red1AmpBP.setTop(red1AmpQL);
					red1TrapBP.setTop(red1TrapQL);
					red1CliBP.setTop(red1CliQL);
					red1CyAvgBP.setTop(red1AvgCyQL);
					red1SpeAvgBP.setTop(red1AvgSpeQL);
					red1AmpAvgBP.setTop(red1AvgAmpQL);
					red1TrapAvgBP.setTop(red1AvgTrapQL);
					red1CliAvgBP.setTop(red1AvgCliQL);
					red2CyBP.setTop(red1CyQL);
					red2SpeBP.setTop(red2SpeQL);
					red2AmpBP.setTop(red2AmpQL);
					red2TrapBP.setTop(red2TrapQL);
					red2CliBP.setTop(red2CliQL);
					red2CyAvgBP.setTop(red2AvgCyQL);
					red2SpeAvgBP.setTop(red2AvgSpeQL);
					red2AmpAvgBP.setTop(red2AvgAmpQL);
					red2TrapAvgBP.setTop(red2AvgTrapQL);
					red2CliAvgBP.setTop(red2AvgCliQL);
					red1CyBP.setCenter(red1Cy);
					red1SpeBP.setCenter(red1Spe);
					red1AmpBP.setCenter(red1Amp);
					red1TrapBP.setCenter(red1Trap);
					red1CliBP.setCenter(red1Cli);
					red1CyAvgBP.setCenter(red1AvgCy);
					red1SpeAvgBP.setCenter(red1AvgSpe);
					red1AmpAvgBP.setCenter(red1AvgAmp);
					red1TrapAvgBP.setCenter(red1AvgTrap);
					red1CliAvgBP.setCenter(red1AvgCli);
					red2CyBP.setCenter(red1Cy);
					red2SpeBP.setCenter(red2Spe);
					red2AmpBP.setCenter(red2Amp);
					red2TrapBP.setCenter(red2Trap);
					red2CliBP.setCenter(red2Cli);
					red2CyAvgBP.setCenter(red2AvgCy);
					red2SpeAvgBP.setCenter(red2AvgSpe);
					red2AmpAvgBP.setCenter(red2AvgAmp);
					red2TrapAvgBP.setCenter(red2AvgTrap);
					red2CliAvgBP.setCenter(red2AvgCli);
					if(mainColor == false) {
						red1CyBP.setId("seMStatBP1");
						red1SpeBP.setId("seMStatBP3");
						red1AmpBP.setId("seMStatBP5");
						red1TrapBP.setId("seMStatBP7");
						red1CliBP.setId("seMStatBP9");
						red1CyAvgBP.setId("seMStatBP2");
						red1SpeAvgBP.setId("seMStatBP4");
						red1AmpAvgBP.setId("seMStatBP6");
						red1TrapAvgBP.setId("seMStatBP8");
						red1CliAvgBP.setId("seMStatBP8");
						red2CyBP.setId("seMStatBP9");
						red2SpeBP.setId("seMStatBP7");
						red2AmpBP.setId("seMStatBP5");
						red2TrapBP.setId("seMStatBP3");
						red2CliBP.setId("seMStatBP1");
						red2CyAvgBP.setId("seMStatBP8");
						red2SpeAvgBP.setId("seMStatBP6");
						red2AmpAvgBP.setId("seMStatBP4");
						red2TrapAvgBP.setId("seMStatBP2");
						red2CliAvgBP.setId("seMStatBP2");
						noData1BP.setId("seMStatBP1");
						VBox red1VB = new VBox(5);
						VBox red2VB = new VBox(5);
						VBox red3VB = new VBox(5);
						red1VB.getChildren().addAll(red1TeamNumBP, red1CyBP, red1SpeBP, red1AmpBP, red1TrapBP, red1CliBP);
						red2VB.getChildren().addAll(red2TeamNumBP, red2CyBP, red2SpeBP, red2AmpBP, red2TrapBP, red2CliBP);
						red3VB.getChildren().add(noData1BP);
						redHB.getChildren().addAll(red1VB, red2VB, red3VB);
					}else {
						red1CyBP.setId("seMStatBP9");
						red1SpeBP.setId("seMStatBP7");
						red1AmpBP.setId("seMStatBP5");
						red1TrapBP.setId("seMStatBP3");
						red1CliBP.setId("seMStatBP1");
						red1CyAvgBP.setId("seMStatBP8");
						red1SpeAvgBP.setId("seMStatBP6");
						red1AmpAvgBP.setId("seMStatBP4");
						red1TrapAvgBP.setId("seMStatBP2");
						red1CliAvgBP.setId("seMStatBP2");
						red2CyBP.setId("seMStatBP1");
						red2SpeBP.setId("seMStatBP3");
						red2AmpBP.setId("seMStatBP5");
						red2TrapBP.setId("seMStatBP7");
						red2CliBP.setId("seMStatBP9");
						red2CyAvgBP.setId("seMStatBP2");
						red2SpeAvgBP.setId("seMStatBP4");
						red2AmpAvgBP.setId("seMStatBP6");
						red2TrapAvgBP.setId("seMStatBP8");
						red2CliAvgBP.setId("seMStatBP8");
						noData1BP.setId("seMStatBP9");
						VBox red1VB = new VBox(5);
						VBox red2VB = new VBox(5);
						VBox red3VB = new VBox(5);
						red1VB.getChildren().addAll(red1TeamNumBP, red1CyBP, red1SpeBP, red1AmpBP, red1TrapBP, red1CliBP);
						red2VB.getChildren().addAll(red2TeamNumBP, red2CyBP, red2SpeBP, red2AmpBP, red2TrapBP, red2CliBP);
						red3VB.getChildren().add(noData1BP);
						redHB.getChildren().addAll(red1VB, red2VB, red3VB);
					}
				}else if(redTeams.size() == 1) {
					System.out.print("BoopseM13red1");
					int teamNum1 = redTeams.get(0).getMatchTeamNum();
					Label red1TeamNumL = new Label(Integer.toString(teamNum1));
					Label noDataLabel1L = new Label("No Data");
					Label noDataLabel2L = new Label("No Data");
					red1TeamNumL.setId("smallTitle");
					noDataLabel1L.setId("smallTitle");
					noDataLabel2L.setId("smallTitle");
					BorderPane red1TeamNumBP = new BorderPane();
					BorderPane noData1BP = new BorderPane();
					BorderPane noData2BP = new BorderPane();
					red1TeamNumBP.setCenter(red1TeamNumL);
					noData1BP.setCenter(noDataLabel1L);
					noData2BP.setCenter(noDataLabel2L);
					Label red1Cy = new Label(Integer.toString(redTeams.get(0).getMatchAmp() + redTeams.get(0).getMatchSpe() + redTeams.get(0).getMatchTrap()));
					red1Cy.setId("avgStat");
					Label red1Amp = new Label(Integer.toString(redTeams.get(0).getMatchAmp()));
					Label red1Spe = new Label(Integer.toString(redTeams.get(0).getMatchSpe()));
					Label red1Trap = new Label(Integer.toString(redTeams.get(0).getMatchTrap()));
					red1Amp.setId("avgStat");
					red1Spe.setId("avgStat");
					red1Trap.setId("avgStat");
					Label red1AvgCy = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgCycles()));
					Label red1AvgSpe = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgSpe()));
					Label red1AvgAmp = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgAmp()));
					Label red1AvgTrap = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgTrap()));
					red1AvgCy.setId("avgStat");
					red1AvgSpe.setId("avgStat");
					red1AvgAmp.setId("avgStat");
					red1AvgTrap.setId("avgStat");
					Label red1Cli = new Label(Integer.toString(redTeams.get(0).getMatchClimb()));
					Label red1AvgCli = new Label(Double.toString(theTL.getATeam(teamNum1).getAvgClimb()));
					red1Cli.setId("avgStat");
					red1AvgCli.setId("avgStat");
					Label red1CyQL = new Label("Match Cycles");
					Label red1SpeQL = new Label("Match Speaker");
					Label red1AmpQL = new Label("Match Amp");
					Label red1TrapQL = new Label("Match Trap");
					Label red1CliQL = new Label("Match Climb");
					Label red1AvgCyQL = new Label("Avg Cycles");
					Label red1AvgSpeQL = new Label("Avg Speaker");
					Label red1AvgAmpQL = new Label("Avg Amp");
					Label red1AvgTrapQL = new Label("Avg Trap");
					Label red1AvgCliQL = new Label("Avg Climb");
					red1CyQL.setId("smallTitle");
					red1SpeQL.setId("smallTitle");
					red1AmpQL.setId("smallTitle");
					red1TrapQL.setId("smallTitle");
					red1CliQL.setId("smallTitle");
					red1AvgCyQL.setId("smallTitle");
					red1AvgSpeQL.setId("smallTitle");
					red1AvgAmpQL.setId("smallTitle");
					red1AvgTrapQL.setId("smallTitle");
					red1AvgCliQL.setId("smallTitle");
					BorderPane red1CyBP = new BorderPane();
					BorderPane red1SpeBP = new BorderPane();
					BorderPane red1AmpBP = new BorderPane();
					BorderPane red1TrapBP = new BorderPane();
					BorderPane red1CliBP = new BorderPane();
					BorderPane red1CyAvgBP = new BorderPane();
					BorderPane red1SpeAvgBP = new BorderPane();
					BorderPane red1AmpAvgBP = new BorderPane();
					BorderPane red1TrapAvgBP = new BorderPane();
					BorderPane red1CliAvgBP = new BorderPane();
					red1CyBP.setTop(red1CyQL);
					red1SpeBP.setTop(red1SpeQL);
					red1AmpBP.setTop(red1AmpQL);
					red1TrapBP.setTop(red1TrapQL);
					red1CliBP.setTop(red1CliQL);
					red1CyAvgBP.setTop(red1AvgCyQL);
					red1SpeAvgBP.setTop(red1AvgSpeQL);
					red1AmpAvgBP.setTop(red1AvgAmpQL);
					red1TrapAvgBP.setTop(red1AvgTrapQL);
					red1CliAvgBP.setTop(red1AvgCliQL);
					red1CyBP.setCenter(red1Cy);
					red1SpeBP.setCenter(red1Spe);
					red1AmpBP.setCenter(red1Amp);
					red1TrapBP.setCenter(red1Trap);
					red1CliBP.setCenter(red1Cli);
					red1CyAvgBP.setCenter(red1AvgCy);
					red1SpeAvgBP.setCenter(red1AvgSpe);
					red1AmpAvgBP.setCenter(red1AvgAmp);
					red1TrapAvgBP.setCenter(red1AvgTrap);
					red1CliAvgBP.setCenter(red1AvgCli);
					if(mainColor == false) {
						red1CyBP.setId("seMStatBP1");
						red1SpeBP.setId("seMStatBP3");
						red1AmpBP.setId("seMStatBP5");
						red1TrapBP.setId("seMStatBP7");
						red1CliBP.setId("seMStatBP9");
						red1CyAvgBP.setId("seMStatBP2");
						red1SpeAvgBP.setId("seMStatBP4");
						red1AmpAvgBP.setId("seMStatBP6");
						red1TrapAvgBP.setId("seMStatBP8");
						red1CliAvgBP.setId("seMStatBP8");
						noData1BP.setId("seMStatBP9");
						noData2BP.setId("seMStatBP1");
						VBox red1VB = new VBox(5);
						VBox red2VB = new VBox(5);
						VBox red3VB = new VBox(5);
						red1VB.getChildren().addAll(red1TeamNumBP, red1CyBP, red1SpeBP, red1AmpBP, red1TrapBP, red1CliBP);
						red2VB.getChildren().add(noData1BP);
						red3VB.getChildren().add(noData2BP);
						redHB.getChildren().addAll(red1VB, red2VB, red3VB);
					}else {
						red1CyBP.setId("seMStatBP9");
						red1SpeBP.setId("seMStatBP7");
						red1AmpBP.setId("seMStatBP5");
						red1TrapBP.setId("seMStatBP3");
						red1CliBP.setId("seMStatBP1");
						red1CyAvgBP.setId("seMStatBP8");
						red1SpeAvgBP.setId("seMStatBP6");
						red1AmpAvgBP.setId("seMStatBP4");
						red1TrapAvgBP.setId("seMStatBP2");
						red1CliAvgBP.setId("seMStatBP2");
						noData1BP.setId("seMStatBP1");
						noData2BP.setId("seMStatBP9");
						VBox red1VB = new VBox(5);
						VBox red2VB = new VBox(5);
						VBox red3VB = new VBox(5);
						red1VB.getChildren().addAll(red1TeamNumBP, red1CyBP, red1SpeBP, red1AmpBP, red1TrapBP, red1CliBP);
						red2VB.getChildren().add(noData1BP);
						red3VB.getChildren().add(noData1BP);
						redHB.getChildren().addAll(red1VB, red2VB, red3VB);
					}
				}else if(redTeams.size() == 0) {
					System.out.print("BoopseM13red0");
					Label noDataLabel1L = new Label("No Data");
					Label noDataLabel2L = new Label("No Data");
					Label noDataLabel3L = new Label("No Data");
					noDataLabel1L.setId("smallTitle");
					noDataLabel2L.setId("smallTitle");
					noDataLabel3L.setId("smallTitle");
					BorderPane noData1BP = new BorderPane();
					BorderPane noData2BP = new BorderPane();
					BorderPane noData3BP = new BorderPane();
					noData1BP.setCenter(noDataLabel1L);
					noData2BP.setCenter(noDataLabel2L);
					noData3BP.setCenter(noDataLabel3L);
					if(mainColor == false) {
						noData1BP.setId("seMStatBP9");
						noData2BP.setId("seMStatBP1");
						noData2BP.setId("seMStatBP9");
						VBox red1VB = new VBox(5);
						VBox red2VB = new VBox(5);
						VBox red3VB = new VBox(5);
						red1VB.getChildren().addAll(noData1BP);
						red2VB.getChildren().add(noData2BP);
						red3VB.getChildren().add(noData3BP);
						redHB.getChildren().addAll(red1VB, red2VB, red3VB);
					}else {
						noData1BP.setId("seMStatBP1");
						noData2BP.setId("seMStatBP9");
						noData2BP.setId("seMStatBP1");
						VBox red1VB = new VBox(5);
						VBox red2VB = new VBox(5);
						VBox red3VB = new VBox(5);
						red1VB.getChildren().addAll(noData1BP);
						red2VB.getChildren().add(noData2BP);
						red3VB.getChildren().add(noData3BP);
						redHB.getChildren().addAll(red1VB, red2VB, red3VB);
					}
				}
				this.add(blueHB, 0, 0);
				this.add(redHB, 1, 0);

			}
			if(event.getSource() == submitPlayB) {
				this.getChildren().clear();
			}
		} catch(Exception e) {
			System.out.println("Error: " + e);
		}
		
	}
}
